Repository kyma-project/website, pull requests merged in 2018-10, with the labels that each got.

#55 Disable whitesource
  Jenkinsfile
Labels: area/ci, bug

#49 Add Blogpost about kubeles and knative
  .gitignore
  src/blog-posts/3-how-kubless-will-be-replaced-with-knative.md
  src/blog-posts/assets/3-serverless-kyma-architecture.png
Labels: area/documentation, enhancement

#51 Change content on landing page
  src/blog-posts/4-blog-post-kyma-at-teched.md
  src/components/docs/external/components/MainPage/MainPage.component.js
  src/components/docs/external/components/Navigation/NavigationList.component.js
  src/components/docs/navigation/NavigationSidebar.js
  src/components/landing/Features.js
  src/components/landing/MakesSpecial.js
  src/components/landing/Mission.js
  src/components/landing/WhatIs.js
  src/components/landing/assets/makesSpecial.svg
  src/components/landing/assets/mission.svg
  src/components/landing/assets/whatIs.svg
  src/components/layout/Banner.js
  src/components/layout/Header.js
  src/components/layout/Navigation.component.js
  src/constants/docs.js
  src/locales/en/LandingPage.json
  src/pages/index.js
  static/global.css
Labels: area/community, area/documentation, enhancement

#60 Fix navigation on the mobile device
  static/global.css
Labels: bug

#54 Enable external links validation on PRs
  governance.Jenkinsfile
  orchestrator.Jenkinsfile
Labels: area/ci, area/documentation, enhancement

#64 Enable WhiteSource in prepare job
  Jenkinsfile
  docs-navigation-builder/Jenkinsfile
Labels: area/ci

#65 Release notes post for 0.4.1
  milv.config.yaml
  src/blog-posts/5-release-notes-041.md
  src/blog-posts/assets/docs-ui.png
  src/blog-posts/assets/filter.png
  src/blog-posts/assets/instance_params.png
  src/blog-posts/assets/multi-api.png
  src/blog-posts/assets/sc_grafana_dashboard.png
Labels: area/community, enhancement

#68 Add corrections
  src/blog-posts/5-release-notes-041.md
Labels: area/documentation

#69 Add a minor fix in the blog post
  src/blog-posts/5-release-notes-041.md
Labels: area/documentation

#70 Add minor fixes in the post
  src/blog-posts/5-release-notes-041.md
Labels: area/documentation

#72 Update banner with new TechEd event
  src/components/layout/Banner.js
Labels: area/community, enhancement

#79 Add aerfio to CODEOWNERS
  CODEOWNERS
Labels: area/community

#81 Update broken links in 5-release-notes-041.md
  src/blog-posts/5-release-notes-041.md
Labels: area/documentation, bug

#83 Copy template for security issues
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  milv.config.yaml
Labels: area/documentation, area/security, enhancement, sig/core

#86 Change dir for Accelerate innovation with Kyma blog post
  src/blog-posts/6-accelerate-innovation-with-kyma.md
Labels: area/community, area/documentation, bug

#87 Provide clear development guide
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/assets/logo.png
  docs/project-structure.md
  docs/write-blog-posts.md
  milv.config.yaml
Labels: area/documentation, enhancement

#76 Add community section in landing page
  src/components/landing/Community.js
  src/components/landing/MakesSpecial.js
  src/components/landing/WhatIs.js
  src/components/landing/assets/community.svg
  src/components/landing/assets/makesSpecial.svg
  src/components/landing/assets/whatIs.svg
  src/components/layout/Footer.js
  src/components/layout/Sprites.js
  src/locales/en/LandingPage.json
  src/locales/en/UI.json
  src/pages/index.js
  static/global.css
  static/img/bottom.svg
  static/img/icons-bg.svg
Labels: area/community, enhancement

#90 Update site metadata
  src/locales/en/UI.json
Labels: area/community, bug

#91 Add google search console verification code
  src/html.js
Labels: area/community, enhancement

#93 Remove images titles for key features
  src/components/landing/features/Connectivity.js
  src/components/landing/features/Extendable.js
  src/components/landing/features/TechIndependent.js
Labels: area/community, bug

#85 Disable external links validation on master
  governance.Jenkinsfile
  orchestrator.Jenkinsfile
Labels: area/ci, area/community, enhancement, priority/critical

#95 Update content of temporary banner
  src/components/layout/Banner.js
Labels: area/community, enhancement

#97 Add animations for svgs on landing page
  src/components/landing/Community.js
  src/components/landing/MakesSpecial.js
  src/components/landing/WhatIs.js
  src/components/landing/assets/community.svg
  src/components/landing/assets/makesSpecial.svg
  src/components/landing/assets/whatIs.svg
  src/components/landing/features/Community.js
  src/components/landing/features/MakesSpecial.js
  src/components/landing/features/WhatIs.js
Labels: needs-ok-to-test

#99 Update dead links
  src/blog-posts/5-release-notes-041.md
Labels: area/community, area/documentation, bug
