Repository kyma-project/website, pull requests merged in 2018-11, with the labels that each got.

#107 Update banner content with ContainerConf invitation
  src/components/layout/Banner.js
Labels: area/community, enhancement

#108 Fix Whitesource scan
  Jenkinsfile
Labels: area/ci, bug

#111 Introduce customizable carousel banner
  docs/README.md
  docs/banner-modification.md
  milv.config.yaml
  package-lock.json
  package.json
  src/banner/banners.json
  src/components/layout/Banner.js
  src/components/layout/Banner/Banner.js
  src/components/layout/Banner/CircleIndicator.js
  src/components/layout/Banner/Icon.js
  src/components/layout/Banner/SlideContent.js
  src/components/layout/Banner/styled.js
  src/components/layout/Header.js
Labels: area/community, area/documentation, enhancement

#115 Fix carousel banner in Safari browser
  docs/banner-modification.md
  src/banner/banners.json
  src/components/layout/Banner/Banner.js
Labels: area/community, bug

#123 Fix WhiteSource config for documentation-generator
  tools/documentation-generator/Jenkinsfile
Labels: area/ci, bug

#114 Rebuild Docs section using static page generator
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/api-extensions/DocsLoader.js
  src/api-extensions/blog-post-pages.js
  src/api-extensions/documentation-pages.js
  src/components/cookiee/CookieeMessageBanner.js
  src/components/docs/Docs.component.js
  src/components/docs/Docs.container.js
  src/components/docs/DocsContent/DocsContent.component.js
  src/components/docs/DocsContent/DocsContent.container.js
  src/components/docs/DocsContent/DocsProcessor.js
  src/components/docs/DocsContent/styled.js
  src/components/docs/DocsRoot.component.js
  src/components/docs/external/MainPage/MainPage.component.js
  src/components/docs/external/MainPage/styled.js
  src/components/docs/external/Navigation/NavigationList.component.js
  src/components/docs/external/components/ColumnsWrapper/ColumnsWrapper.component.js
  src/components/docs/external/components/ContentWrapper/ContentWrapper.component.js
  src/components/docs/external/components/ContentWrapper/ContentWrapper.container.js
  src/components/docs/external/components/MainPage/MainPage.component.js
  src/components/docs/external/helpers/helpers.js
  src/components/docs/navigation/NavigationSidebar.js
  src/components/docs/navigation/VersionSwitcher.js
  src/components/layout/Banner/Banner.js
  src/components/layout/Banner/SlideContent.js
  src/components/layout/Banner/styled.js
  src/components/loading/LoadingIndicator.js
  src/constants/docs.js
  src/helpers/DocsFetcher.js
  src/helpers/docsPath.js
  src/helpers/tokenize.js
  src/pages/docs.js
  src/templates/Documentation.js
Labels: area/community, enhancement

#124 Downgrade react-cookie-banner
  Jenkinsfile
  package-lock.json
  package.json
  src/components/cookiee/CookieeMessageBanner.js
Labels: area/ci, bug

#125 Fix Docs version switcher behavior
  src/api-extensions/documentation-pages.js
  src/components/docs/DocsRoot.component.js
  src/components/docs/external/MainPage/MainPage.component.js
  src/components/docs/external/Navigation/NavigationList.component.js
  src/components/docs/navigation/NavigationSidebar.js
  src/helpers/docsPath.js
  src/templates/Documentation.js
Labels: area/community, bug

#127 Add blog post about relase notes 0.5
  src/blog-posts/7-release-notes-05.md
  src/blog-posts/assets/alerts_9.png
  src/blog-posts/assets/bind_application_1.png
  src/blog-posts/assets/bind_application_3.png
  src/blog-posts/assets/bound_applications.png
  src/blog-posts/assets/console_1.png
  src/blog-posts/assets/console_2.PNG
  src/blog-posts/assets/jwks_authentication2_2.png
  src/blog-posts/assets/jwks_authentication_1.png
  src/blog-posts/assets/service_instances.png
  src/blog-posts/assets/unsaved_changes_3.png
Labels: area/community, enhancement

#129 Fix screenshot on 0.5 release blog-post
  src/blog-posts/assets/console_2.PNG
Labels: area/community, bug

#130 Add latest route for docs
  package-lock.json
  src/api-extensions/documentation-pages.js
  src/components/docs/DocsContent/DocsContent.container.js
  src/components/docs/DocsContent/DocsProcessor.js
  src/components/docs/external/MainPage/MainPage.component.js
  src/components/docs/navigation/NavigationSidebar.js
Labels: area/community, bug

#135 Remove kyma-project.io from milv config
  milv.config.yaml
Labels: area/community, area/documentation, bug

#141 Modify descriptions on landing page
  src/components/landing/Features.js
  src/components/landing/MakesSpecial.js
  src/components/landing/WhatIs.js
  src/locales/en/LandingPage.json
Labels: area/community, area/documentation, enhancement
