Repository kyma-project/website, pull requests merged in 2018-12, with the labels that each got.

#145 Create post about kyma members attending kubecon
  src/blog-posts/8-kyma-at-kubecon.md
Labels: area/community, area/documentation, enhancement

#140 Update banners with KubeCon event.json
  src/banner/banners.json
Labels: area/community, enhancement

#149 Fix spelling mistake in 8-kyma-at-kubecon.md
  src/blog-posts/8-kyma-at-kubecon.md
Labels: area/community

#155 Add Website pipeline for Prow CI
  Makefile
  scripts/generate-docs.sh
  scripts/helpers/git-config.sh
  scripts/prepare-website.sh
Labels: area/ci, area/community

#152 Update sentence in the kyma at kubecon blog post.md
  src/blog-posts/8-kyma-at-kubecon.md
Labels: area/documentation

#154 Add blog post about xxxlutz.md
  src/blog-posts/9-xxxlutz-video.md
Labels: area/community, area/documentation

#159 Remove Jenkins from Website
  governance.Jenkinsfile
  orchestrator.Jenkinsfile
Labels: area/ci, area/community

#157 Release 0.6 blog post
  src/blog-posts/9-release-0.6-plan.md
Labels: WIP

#119 Update 4-blog-post-kyma-at-teched.md
  src/blog-posts/4-blog-post-kyma-at-teched.md
Labels: area/community, enhancement

#163 Improve styles for docs and blogs
  src/components/blog/PostFooter.js
  src/components/blog/PostHeader.js
  src/components/blog/PostsWrapper.js
  src/components/content/MDContent.js
  src/components/docs/DocsContent/styled.js
  src/components/docs/external/MainPage/MainPage.component.js
  src/components/docs/external/MainPage/styled.js
  src/components/docs/navigation/VersionSwitcher.js
Labels: area/community, area/documentation, enhancement

#165 Add chain for anchors
  gatsby-config.js
  package-lock.json
  package.json
  src/api-extensions/constants.js
  src/api-extensions/documentation-pages.js
  src/api-extensions/links-parser.js
  src/api-extensions/rewrite-links.js
  src/components/content/MDContent.js
  src/components/docs/DocsContent/DocsContent.component.js
  src/components/docs/DocsContent/styled.js
  src/components/docs/navigation/VersionSwitcher.js
  src/templates/Documentation.js
  static/global.css
Labels: area/documentation, enhancement

#166 Show excerpt on blog post list
  docs/write-blog-posts.md
  gatsby-config.js
  milv.config.yaml
  package-lock.json
  package.json
  src/blog-posts/0-introducing.md
  src/blog-posts/1-kyma-knative-progress-report.md
  src/blog-posts/10-release-0.6-plan.md
  src/blog-posts/2-start-with-person-service.md
  src/blog-posts/3-replacing-kubeless-with-knative.md
  src/blog-posts/4-blog-post-kyma-at-teched.md
  src/blog-posts/5-release-notes-041.md
  src/blog-posts/6-accelerate-innovation-with-kyma.md
  src/blog-posts/7-release-notes-05.md
  src/blog-posts/8-kyma-at-kubecon.md
  src/blog-posts/9-xxxlutz-video.md
  src/components/blog/Post.js
  src/components/content/MDContent.js
  src/config/colors.js
  src/pages/blog.js
Labels: area/community, area/documentation, enhancement
