Repository kyma-project/website, pull requests merged in 2018-09, with the labels that each got.

#28 Enable Whitesource
  Jenkinsfile
  docs-navigation-builder/package-lock.json
  package-lock.json
  package.json
  src/components/cookiee/CookieeMessageBanner.js
  src/components/docs/external/components/ContentWrapper/ContentWrapper.component.js
Labels: WIP

#37 Change behaviour of navigation to display type first
  docs-navigation-builder/index.js
  src/components/docs/external/components/ContentWrapper/ContentWrapper.component.js
  src/components/docs/external/components/Navigation/NavigationList.component.js
Labels: area/community, enhancement

#38 Provide links to slack, linkedin, youtube
  .gitignore
  src/components/layout/Footer.js
  src/components/layout/Navigation.component.js
  src/components/layout/Sprites.js
  src/locales/en/UI.json
  static/global.css
Labels: enhancement

#44 Update broken link and rename post path
  src/blog-posts/2-start-with-person-service.md
Labels: area/community, bug

#47 Bump navigation-builder and content-to-json-generator images
  scripts/prepare-docs.sh
Labels: area/security, security/critical
