Repository kyma-project/website, pull requests merged in 2019-05, with the labels that each got.

#291 Improve instruction on how to link in the RNs
  docs/write-blog-posts.md
Labels: area/documentation, enhancement, quality/content

#294 Fix dead links
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
Labels: area/documentation, bug

#281 Update Codeowners and add markdown linter
  .markdownlintrc
  CODEOWNERS
  Makefile
  content/blog-posts/2019-03-14-release-notes-0.8/index.md
  content/blog-posts/2019-03-15-release-0.9-plan/index.md
  content/blog-posts/2019-04-18-release-1.0-plan/index.md
  content/blog-posts/2019-04-25-release-notes-1.0/index.md
  docs/internationalization.md
  docs/project-structure.md
  docs/write-blog-posts.md
  package-lock.json
  package.json
Labels: area/documentation, enhancement

#276 Add fetchers for capabilities and tickets for roadmap
  milv.config.yaml
  scripts/before-commit.sh
  scripts/prepare-content.sh
  tools/content-loader/.gitignore
  tools/content-loader/README.md
  tools/content-loader/bin/main.ts
  tools/content-loader/package-lock.json
  tools/content-loader/package.json
  tools/content-loader/src/config.ts
  tools/content-loader/src/github-client/git-client.ts
  tools/content-loader/src/github-client/github-client.ts
  tools/content-loader/src/github-client/github-graphql-client.ts
  tools/content-loader/src/github-client/zenhub-client.ts
  tools/content-loader/src/helpers/copy-resources.ts
  tools/content-loader/src/helpers/get-files-paths.ts
  tools/content-loader/src/helpers/get-unique.ts
  tools/content-loader/src/helpers/index.ts
  tools/content-loader/src/helpers/remove-dir.ts
  tools/content-loader/src/helpers/remove-html-comments.ts
  tools/content-loader/src/helpers/write-to-json.ts
  tools/content-loader/src/prepare-docs/branches-checking.ts
  tools/content-loader/src/prepare-docs/branches-serializer.ts
  tools/content-loader/src/prepare-docs/config.ts
  tools/content-loader/src/prepare-docs/copy-docs.ts
  tools/content-loader/src/prepare-docs/docs-versions.ts
  tools/content-loader/src/prepare-docs/index.ts
  tools/content-loader/src/prepare-docs/release-fetcher.ts
  tools/content-loader/src/prepare-docs/tag-fetcher.ts
  tools/content-loader/src/prepare-roadmap-content/capabilities-fetcher.ts
  tools/content-loader/src/prepare-roadmap-content/config.ts
  tools/content-loader/src/prepare-roadmap-content/index.ts
  tools/content-loader/src/prepare-roadmap-content/tickets-extractor.ts
  tools/content-loader/src/prepare-roadmap-content/tickets-fetcher.ts
  tools/content-loader/src/prepare-roadmap-content/types.ts
  tools/content-loader/tslint.json
  tsconfig.json
  tslint.json
Labels: area/ci, area/community, enhancement

#295 Update `publish-website` target
  Makefile
Labels: area/ci, bug

#296 Bump image of content-loader tool
  scripts/prepare-content.sh
Labels: area/core-and-supporting, enhancement

#297 Fix capabilities description and disable button to top
  content/i18n/en/roadmap.json
  src/common/hooks/useDropdown.ts
  src/components/layout/Layout.tsx
  src/components/roadmap/Overview.tsx
  src/components/roadmap/styled.ts
Labels: area/documentation, bug

#298 Adjust background to roadmap
  src/components/roadmap/Tickets/Header.tsx
  src/components/roadmap/Tickets/styled.ts
  static/img/roadmap-top.png
  static/img/roadmap-top.svg
Labels: enhancement

#299 Adjust content loader to new docs architecture
  tools/content-loader/.gitignore
  tools/content-loader/Makefile
  tools/content-loader/package-lock.json
  tools/content-loader/package.json
  tools/content-loader/src/helpers/copy-resources.ts
  tools/content-loader/src/helpers/file-exists.ts
  tools/content-loader/src/helpers/index.ts
  tools/content-loader/src/helpers/read-file.ts
  tools/content-loader/src/helpers/read-yaml.ts
  tools/content-loader/src/helpers/write-to-json.ts
  tools/content-loader/src/helpers/write-to-yaml.ts
  tools/content-loader/src/prepare-docs/adjust-new-architecture.ts
  tools/content-loader/src/prepare-docs/copy-docs.ts
Labels: area/core-and-supporting, area/documentation, enhancement

#305 Bump content loader tool image
  scripts/prepare-content.sh
Labels: area/ci, area/documentation, enhancement

#306 Add missing ids for capabilities
  src/components/roadmap/Svg.tsx
  src/components/roadmap/Svgs/Serverless.tsx
Labels: area/core-and-supporting, enhancement

#289 Move kyma-project.io to netlify
  .babelrc
  .gitignore
  Makefile
  README.md
  gatsby-config.js
  netlify.toml
  netlify/functions/kyma-organization-github-hook.ts
  netlify/functions/kyma-organization-github-hook/index.ts
  netlify/functions/kyma-organization-github-hook/issues.event.ts
  netlify/functions/kyma-organization-github-hook/pull-request.event.ts
  netlify/functions/kyma-organization-github-hook/release.event.ts
  netlify/functions/utils/github-client.ts
  package-lock.json
  package.json
  scripts/prepare-content.sh
  scripts/publish-website.sh
  src/components/layout/Footer.tsx
  src/components/layout/styled.tsx
  static/img/netlify.svg
  tools/content-loader/Dockerfile
  tools/content-loader/Makefile
  tsconfig.json
Labels: area/ci, area/core-and-supporting, enhancement

#309 Add additional descriptions in roadmap
  .prettierignore
  Makefile
  README.md
  content/i18n/en/roadmap.json
  src/components/roadmap/Capabilities/Navigation.tsx
  src/components/roadmap/Dropdown/Dropdown.tsx
  src/components/roadmap/Dropdown/styled.ts
  src/components/roadmap/Overview.tsx
  src/components/roadmap/Tickets/Header.tsx
  src/components/roadmap/Tickets/Tickets.tsx
  src/components/roadmap/Tickets/styled.ts
  tools/content-loader/Makefile
Labels: area/community, enhancement

#310 Rename function to trigger master build
  netlify/functions/kyma-organization-github-hook.ts
  netlify/functions/master-build.ts
  netlify/functions/master-build/index.ts
  netlify/functions/master-build/issues.event.ts
  netlify/functions/master-build/pull-request.event.ts
  netlify/functions/master-build/release.event.ts
Labels: enhancement

#312 Update codeowners
  CODEOWNERS
Labels: enhancement

#313 Update codeowners vol 2
  CODEOWNERS
Labels: enhancement

#314 Fix small bugs in roadmap
  src/components/roadmap/Dropdown/styled.ts
  src/components/roadmap/Tickets/Release.tsx
  src/components/roadmap/Tickets/styled.ts
Labels: bug

#316 Enable roadmap in navigation
  src/components/layout/Navigation.tsx
  src/components/layout/styled.tsx
Labels: area/community, enhancement

#293 Add 1.1 release notes
  content/blog-posts/2019-05-17-release-notes-1.1/add-ons-1.png
  content/blog-posts/2019-05-17-release-notes-1.1/add-ons-2.png
  content/blog-posts/2019-05-17-release-notes-1.1/index.md
  content/blog-posts/2019-05-17-release-notes-1.1/namespaces-overview.png
  content/blog-posts/2019-05-17-release-notes-1.1/provision-only-once.png
Labels: area/documentation

#311 Fix bullet points in Tip/Note/Caution
  src/components/shared/NotePanel/styled.ts
  src/components/shared/ReactMarkdown/components/Blockquote.tsx
Labels: area/community, area/documentation

#300 Fix banner on mobile devices
  docs/banner-modification.md
  src/components/layout/SlidesBanner/SlideIcon.tsx
  src/components/layout/SlidesBanner/SlidesBanner.tsx
  src/components/layout/SlidesBanner/styled.ts
  src/components/layout/SlidesBanner/types.ts
Labels: enhancement

#319 Fix cookie banner
  src/components/layout/CookiesBanner.tsx
  src/components/layout/styled.tsx
Labels: bug

#320 Add blog post that introduces readmap view
  content/blog-posts/2019-05-20-transparency-through-roadmap/index.md
Labels: area/community

#321 Fix broken links
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
Labels: area/documentation

#322 Generate sitemap for whole kyma-project.io
  config.json
  gatsby-config.js
  package-lock.json
  package.json
Labels: area/community, enhancement

#324 Fix render images in ReactMarkdown
  src/components/shared/ReactMarkdown/components/Code/index.tsx
  src/components/shared/ReactMarkdown/index.tsx
  src/components/shared/ReactMarkdown/parseHTML/Tabs.tsx
Labels: bug

#315 Add search functionality
  .eslintignore
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/common/constants.ts
  src/common/icons.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navigation.tsx
  src/components/layout/assets/LogoFirst.tsx
  src/components/layout/assets/LogoSecond.tsx
  src/components/layout/styled.tsx
  src/components/search/Algolia.tsx
  src/components/search/AlgoliaWrapper.ts
  src/components/search/GoogleCustomSearchElement.tsx
  src/components/search/Search.tsx
  src/components/search/styled.ts
  src/pages/search.tsx
  static/css/docsearch.min.css
  static/css/fonts.css
  static/global.css
  static/js/docsearch.min.js
Labels: area/community, area/documentation, enhancement

#327 Adjust algolia config to config in docsearch/configs repo
  src/components/layout/Layout.tsx
  src/components/layout/SiteMetadata.tsx
  src/components/search/Algolia.tsx
  src/templates/Docs.tsx
Labels: enhancement

#328 Fix banner appearing when there's no active events
  src/components/layout/SlidesBanner/SlidesBanner.tsx
Labels: area/community, bug

#329 Update algolia config
  src/components/search/Algolia.tsx
Labels: enhancement

#331 Add SAAS to early adopters
  src/components/landingPage/EarlyAdopters/EarlyAdopters.tsx
  src/components/landingPage/EarlyAdopters/EarlyAdoptersListItem.tsx
  src/components/landingPage/styled.ts
  src/components/search/Algolia.tsx
  static/img/early-adopters/saas.svg
Labels: enhancement

#333 Fix bad rendering code in tabs
  package-lock.json
  package.json
  src/components/shared/ReactMarkdown/index.tsx
Labels: bug

#335 Add google analytics in head
  gatsby-config.js
  package-lock.json
  package.json
Labels: enhancement

#337 Update dependencies of content-loader
  tools/content-loader/package-lock.json
  tools/content-loader/package.json
Labels: security/high

#343 Update content/docs/versions.json
  content/docs/versions.json
Labels: area/documentation
