Repository kyma-project/website, pull requests merged in 2019-06, with the labels that each got.

#348 Add links to the logos in the early adopters section
  content/early-adopters/early-adopters.yml
  gatsby-config.js
  plugins/gatsby-plugin-early-adopters-yml/gatsby-node.js
  plugins/gatsby-plugin-early-adopters-yml/package.json
  src/components/landingPage/EarlyAdopters/EarlyAdopters.tsx
  src/components/landingPage/EarlyAdopters/EarlyAdoptersListItem.tsx
  src/components/landingPage/LandingPage.tsx
  src/components/landingPage/styled.ts
Labels: area/community, enhancement

#351 Change number of fetching epic issues in content-loader
  tools/content-loader/src/prepare-roadmap-content/tickets-fetcher.ts
Labels: bug

#318 Enable navigation between tabs
  Makefile
  gatsby-config.js
  package-lock.json
  package.json
  src/common/hooks/useDropdown.ts
  src/common/hooks/useLocation.ts
  src/common/i18n/FormattedMessage.tsx
  src/common/icons.ts
  src/common/state/GlobalState.ts
  src/common/state/usePopup.ts
  src/common/state/useScrollSpy.ts
  src/common/styled/GlobalStyles.tsx
  src/common/styled/Grid.ts
  src/common/utils.ts
  src/common/utils/scrollToAnchor.ts
  src/common/utils/toKebabCase.ts
  src/components/blog/BlogPage.tsx
  src/components/blog/Post.tsx
  src/components/blog/content/PostContent.tsx
  src/components/docs/navigation/leftNavigation/LeftNavigation.tsx
  src/components/docs/navigation/leftNavigation/NavigationList/NavigationList.tsx
  src/components/docs/navigation/leftNavigation/NavigationList/NavigationSection.tsx
  src/components/docs/root/RootDocs.tsx
  src/components/docs/types.ts
  src/components/layout/BackToTop.tsx
  src/components/layout/Popup.tsx
  src/components/roadmap/Modal/Modal.tsx
  src/components/shared/Icon/index.tsx
  src/components/shared/Link/index.tsx
  src/components/shared/Modal/index.tsx
  src/components/shared/ReactMarkdown/components/Blockquote.tsx
  src/components/shared/ReactMarkdown/components/Code/CopyButton.tsx
  src/components/shared/ReactMarkdown/components/EmbedVideo/helpers.ts
  src/components/shared/ReactMarkdown/components/Heading.tsx
  src/components/shared/ReactMarkdown/components/Link.tsx
  src/components/shared/ReactMarkdown/components/TableCell.tsx
  src/components/shared/ReactMarkdown/components/ThematicBreak.tsx
  src/components/shared/ReactMarkdown/helpers.ts
  src/components/shared/ReactMarkdown/index.tsx
  src/components/shared/ReactMarkdown/parseHTML/Tabs.tsx
  src/components/shared/ReactMarkdown/parseHTML/index.tsx
  src/components/shared/Tabs/index.tsx
  src/components/shared/Tooltip/styled.ts
  src/custom.d.ts
  tsconfig.json
  tslint.json
Labels: area/community, area/documentation

#357 Fix multiple the same nodes in navigation in newest versions
  tools/content-loader/src/prepare-docs/adjust-new-architecture.ts
Labels: bug

#358 Fix rendering YT links on blog posts
  src/components/shared/ReactMarkdown/components/EmbedVideo/helpers.ts
Labels: bug

#347 Enable search on whole website
  content/i18n/en/search.json
  gatsby/onCreateWebpackConfig.js
  package-lock.json
  src/common/constants.ts
  src/common/hooks/useToggle.ts
  src/common/i18n/locales.ts
  src/common/i18n/types.ts
  src/common/icons.ts
  src/common/utils.ts
  src/components/landingPage/styled.ts
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navigation.tsx
  src/components/layout/Search/Input.tsx
  src/components/layout/Search/Search.tsx
  src/components/layout/Search/styled.ts
  src/components/layout/SiteMetadata.tsx
  src/components/layout/service.ts
  src/components/layout/styled.tsx
  src/components/roadmap/Dropdown/Dropdown.tsx
  src/components/search/Algolia.tsx
  src/components/search/AlgoliaWrapper.ts
  src/components/search/GoogleCustomSearchElement.tsx
  src/components/search/Search.tsx
  src/components/search/styled.ts
  src/components/shared/Button/index.tsx
  src/components/shared/Icon/index.tsx
  src/components/shared/Tooltip/index.tsx
  src/components/shared/Tooltip/styled.ts
  src/custom.d.ts
  src/pages/search.tsx
  src/templates/Docs.tsx
  tsconfig.json
Labels: area/documentation, enhancement

#355 Release Notes for 1.2 Istanbul
  content/blog-posts/2019-06-13-release-notes-1.2/index.md
Labels: area/documentation

#362 Remove filter by version in search
  src/components/layout/Search/Search.tsx
Labels: area/core-and-supporting, bug

#365 Fix type errors
  Makefile
  package-lock.json
  package.json
  src/common/i18n/injectIntl.tsx
  src/common/i18n/types.ts
  src/components/blog/PostHeader.tsx
  src/components/docs/DocsPage.tsx
  src/components/docs/navigation/leftNavigation/LeftNavigation.tsx
  src/components/docs/navigation/leftNavigation/NavigationList/NavigationGroup.tsx
  src/components/docs/navigation/leftNavigation/NavigationList/NavigationSection.tsx
  src/components/docs/navigation/leftNavigation/VersionSwitcher/VersionSwitcher.tsx
  src/components/docs/root/RootDocs.tsx
  src/components/layout/Search/Search.tsx
  src/components/shared/ReactMarkdown/components/Code/CopyButton.tsx
  src/components/shared/ReactMarkdown/components/Code/index.tsx
  src/components/shared/ReactMarkdown/components/EmbedVideo/helpers.ts
  src/custom.d.ts
  src/window.d.ts
Labels: area/core-and-supporting, enhancement
