Repository kyma-project/website, pull requests merged in 2019-02, with the labels that each got.

#195 Fix broken links in blog posts
  milv.config.yaml
  src/api-extensions/links-parser.js
  src/blog-posts/5-release-notes-041.md
Labels: area/documentation, bug

#192 Release Notes 0.7
  milv.config.yaml
  src/blog-posts/13-release-notes-07.md
Labels: area/documentation

#202 Correct broken links
  src/blog-posts/13-release-notes-07.md
Labels: area/documentation

#203 fix internal links
  src/blog-posts/13-release-notes-07.md
Labels: area/documentation

#206 Add content-loader tool
  tools/content-loader/.eslinterrc
  tools/content-loader/.gitignore
  tools/content-loader/.prettierrc
  tools/content-loader/Dockerfile
  tools/content-loader/Makefile
  tools/content-loader/README.md
  tools/content-loader/package-lock.json
  tools/content-loader/package.json
  tools/content-loader/src/config.js
  tools/content-loader/src/documentation/checking.js
  tools/content-loader/src/documentation/config.js
  tools/content-loader/src/documentation/copy.js
  tools/content-loader/src/documentation/docsBranches.js
  tools/content-loader/src/documentation/docsReleases.js
  tools/content-loader/src/documentation/generateDocsVersions.js
  tools/content-loader/src/documentation/index.js
  tools/content-loader/src/helpers/gitClient.js
  tools/content-loader/src/helpers/githubClient.js
  tools/content-loader/src/index.js
Labels: area/documentation, enhancement

#214 Add permission to scripts
  scripts/prepare-content.sh
  scripts/publish-website.sh
Labels: bug

#211 Add new blog post about the CORE SIG
  src/blog-posts/15-blog-post-core-sig.md
Labels: area/documentation

#216 Change destination of core-sig blog post
  content/blog-posts/2019-02-20-core-sig/index.md
Labels: area/community, area/documentation

#204 Restructuring docs folder
  docs/README.md
  docs/banner-modification.md
  docs/internationalization.md
  docs/project-structure.md
  docs/write-blog-posts.md
  milv.config.yaml
Labels: area/community, area/documentation, enhancement

#219 Improve Key Features section
  src/components/landingPage/KeyFeatures.tsx
  src/components/landingPage/styled.ts
  src/components/shared/Button/index.tsx
Labels: area/community, enhancement
