Repository kyma-project/website, pull requests merged in 2019-07, with the labels that each got.

#354 Extend Wordpress blog post
  content/blog-posts/2019-07-08-extend-wordpress/add-wordpress-instance.png
  content/blog-posts/2019-07-08-extend-wordpress/application.png
  content/blog-posts/2019-07-08-extend-wordpress/binding.png
  content/blog-posts/2019-07-08-extend-wordpress/comments.png
  content/blog-posts/2019-07-08-extend-wordpress/console.png
  content/blog-posts/2019-07-08-extend-wordpress/index.md
  content/blog-posts/2019-07-08-extend-wordpress/kyma-connector.png
  content/blog-posts/2019-07-08-extend-wordpress/wordpress-deployment.yaml
Labels: area/documentation

#368 Add RSS Feed to website
  config.json
  gatsby-config.js
  package-lock.json
  package.json
  src/components/blog/BlogPage.tsx
  src/components/blog/assets/RSS_46x46_default.svg
  src/components/blog/assets/RSS_46x46_hover.svg
  src/components/blog/styled.ts
  src/pages/index.tsx
Labels: area/community, area/core-and-supporting

#372 Add 1.3 release notes
  content/blog-posts/2019-07-12-release-notes-1.3/console-backend.png
  content/blog-posts/2019-07-12-release-notes-1.3/console-backend2.png
  content/blog-posts/2019-07-12-release-notes-1.3/documentation-component.png
  content/blog-posts/2019-07-12-release-notes-1.3/index.md
Labels: area/documentation, quality/release

#377 Fix security vulnerabilities from packages
  docs/write-blog-posts.md
  gatsby/pages/onCreatePage.ts
  package-lock.json
  package.json
Labels: security/high

#378 Fix display of images
  plugins/gatsby-plugin-copy-files/gatsby-node.js
Labels: bug

#384 Enable html tags in react-markdown
  src/components/shared/ReactMarkdown/parseHTML/index.tsx
Labels: bug

#387 Fix security vulnerabilities in tools/content-loader
  tools/content-loader/package-lock.json
Labels: security/high

#367 Add blog post about Kyma birthday
  content/banner/slides.yml
  content/blog-posts/2019-07-24-happy-birthday-kyma/2019-05-02_kyma_golive_netconomy.jpg
  content/blog-posts/2019-07-24-happy-birthday-kyma/birthday.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/chair.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/early-adopters.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/google-next.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
  content/blog-posts/2019-07-24-happy-birthday-kyma/kube-con-seattle.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/kyma-sap.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/landscape-screen.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/lysy-seattle.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/sig-member.png
  content/blog-posts/2019-07-24-happy-birthday-kyma/swag.png
  milv.config.yaml
  src/components/blog/styled.ts
Labels: area/community, area/documentation

#390 Add additional blog post fixes
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
Labels: area/documentation

#395 Check if file is symlink and remove it from paths
  tools/content-loader/src/helpers/get-files-paths.ts
Labels: bug

#396 Add the kyma and knative blog post
  content/blog-posts/2019-07-24-kyma-and-knative-turning-one/index.md
  content/blog-posts/2019-07-24-kyma-and-knative-turning-one/wheels.png
Labels: area/documentation

#398 Fix a dead link
  content/blog-posts/2019-05-17-release-notes-1.1/index.md
Labels: area/documentation

#399 Fix broken links
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
  content/blog-posts/2019-06-13-release-notes-1.2/index.md
Labels: area/documentation

#400 Update stale bot settings to exclude epics
  .github/stale.yml
Labels: area/community
