Repository kyma-project/website, pull requests merged in 2019-03, with the labels that each got.

#220 Add overview excerpt in post about sig core
  content/blog-posts/2019-02-20-core-sig/index.md
Labels: area/community, bug

#222 Fix broken links in 0.7 version
  CODEOWNERS
  content/docs/fix-links.json
  gatsby/createPages/docsPages/fixLinks.js
Labels: area/documentation, bug

#224 Improve scrollbar styles
  src/common/styled/mixins.ts
  src/components/docs/navigation/leftNavigation/NavigationList/styled.ts
  src/components/shared/ReactMarkdown/components/Code/index.tsx
Labels: area/documentation, bug

#228 Remove documentation-generator-tool
  tools/documentation-generator/.eslinterrc
  tools/documentation-generator/.gitignore
  tools/documentation-generator/.prettierrc
  tools/documentation-generator/Dockerfile
  tools/documentation-generator/Makefile
  tools/documentation-generator/README.md
  tools/documentation-generator/package-lock.json
  tools/documentation-generator/package.json
  tools/documentation-generator/src/config.js
  tools/documentation-generator/src/generators/configuration.js
  tools/documentation-generator/src/generators/documentation.js
  tools/documentation-generator/src/generators/external/documentation/common/evaluator.js
  tools/documentation-generator/src/generators/external/documentation/common/helpers.js
  tools/documentation-generator/src/generators/external/documentation/common/raml.js
  tools/documentation-generator/src/generators/external/documentation/generator.js
  tools/documentation-generator/src/generators/manifest.js
  tools/documentation-generator/src/generators/navigation.js
  tools/documentation-generator/src/helpers/git.js
  tools/documentation-generator/src/helpers/github.js
  tools/documentation-generator/src/helpers/release.js
  tools/documentation-generator/src/index.js
Labels: area/ci

#226 Add copy of code blocks functionality
  content/i18n/en/utils.json
  package-lock.json
  package.json
  src/common/i18n/locales.ts
  src/common/i18n/types.ts
  src/common/icons.ts
  src/common/state/GlobalState.ts
  src/common/state/index.ts
  src/common/state/nest.tsx
  src/common/state/usePopup.ts
  src/components/layout/Layout.tsx
  src/components/layout/Popup.tsx
  src/components/shared/Icon/index.tsx
  src/components/shared/ReactMarkdown/components/Code/CopyButton.tsx
  src/components/shared/ReactMarkdown/components/Code/index.tsx
  src/components/shared/Tooltip/index.tsx
  src/components/shared/Tooltip/styled.ts
  src/custom.d.ts
Labels: area/documentation, enhancement

#229 Add tabs component
  content/blog-posts/2019-02-20-core-sig/index.md
  content/docs/0.7/kyma/docs/01-06-how-to-start.md
  content/docs/0.7/security/docs/02-01-security.md
  src/common/state/GlobalState.ts
  src/common/state/usePopup.ts
  src/common/state/useScrollSpy.ts
  src/components/docs/navigation/leftNavigation/NavigationList/NavigationList.tsx
  src/components/docs/navigation/scrollSpy/ScrollSpy.tsx
  src/components/docs/root/DocsPageWrapper.tsx
  src/components/docs/root/RootDocs.tsx
  src/components/layout/Popup.tsx
  src/components/shared/ReactMarkdown/components/Code/CopyButton.tsx
  src/components/shared/ReactMarkdown/helpers.ts
  src/components/shared/ReactMarkdown/index.tsx
  src/components/shared/ReactMarkdown/parseHTML/Tabs.tsx
  src/components/shared/ReactMarkdown/parseHTML/index.tsx
  src/components/shared/Tabs/Tab.tsx
  src/components/shared/Tabs/index.tsx
  src/components/shared/Tabs/styled.ts
  src/custom.d.ts
Labels: area/documentation, enhancement

#238 Change the codeowners file
  CODEOWNERS
Labels: area/documentation

#235 Kyma 0.8 Edmonton release notes
  content/blog-posts/2018-03-14-release-notes-0.8/copy_button.png
  content/blog-posts/2018-03-14-release-notes-0.8/early_adopters.png
  content/blog-posts/2018-03-14-release-notes-0.8/index.md
  content/blog-posts/2018-03-14-release-notes-0.8/link_icon.png
  content/blog-posts/2018-03-14-release-notes-0.8/monitoring_minio.png
  content/blog-posts/2018-03-14-release-notes-0.8/odata.png
  content/blog-posts/2018-03-14-release-notes-0.8/panels.png
  content/blog-posts/2018-03-14-release-notes-0.8/provision_once.png
  content/blog-posts/2018-03-14-release-notes-0.8/scroll_bar_bug.png
  content/blog-posts/2018-03-14-release-notes-0.8/tabs_layout.png
Labels: area/documentation

#242 Remove duplicate of 0.8 release notes blog post
  content/blog-posts/2018-03-14-release-notes-0.8/copy_button.png
  content/blog-posts/2018-03-14-release-notes-0.8/early_adopters.png
  content/blog-posts/2018-03-14-release-notes-0.8/index.md
  content/blog-posts/2018-03-14-release-notes-0.8/link_icon.png
  content/blog-posts/2018-03-14-release-notes-0.8/monitoring_minio.png
  content/blog-posts/2018-03-14-release-notes-0.8/odata.png
  content/blog-posts/2018-03-14-release-notes-0.8/panels.png
  content/blog-posts/2018-03-14-release-notes-0.8/provision_once.png
  content/blog-posts/2018-03-14-release-notes-0.8/scroll_bar_bug.png
  content/blog-posts/2018-03-14-release-notes-0.8/tabs_layout.png
Labels: area/community, bug

#244 Fix wrong date on blog posts
  content/i18n/en/utils.json
  src/components/blog/BlogPage.tsx
  src/components/blog/Post.tsx
  src/components/blog/PostHeader.tsx
  src/components/blog/queries.ts
  src/components/blog/types.ts
  src/templates/BlogPost.tsx
  src/templates/Docs.tsx
Labels: area/community, area/documentation, bug

#239 Blog post with Release 0.9 plan
  content/blog-posts/2019-03-15-release-0.9-plan/index.md
Labels: area/documentation

#245 Fix filter for markdown files in content-loader tool
  content/docs/0.6/kyma/docs/036-inst-xip.io-domain.md
  content/docs/0.7/kyma/docs/01-06-how-to-start.md
  content/docs/0.7/kyma/docs/04-06-gke-xip.io-domain.md
  content/docs/0.7/kyma/docs/04-07-aks-xip.io-domain.md
  content/docs/0.7/security/docs/02-01-security.md
  content/docs/0.8/kyma/docs/04-06-gke-xip.io-domain.md
  content/docs/0.8/kyma/docs/04-07-aks-xip.io-domain.md
  tools/content-loader/src/documentation/copy.js
Labels: area/documentation, bug

#249 Fix WG Knative link in 0.6 RN
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
Labels: area/documentation, bug
