Repository kyma-project/website, pull requests merged in 2019-04, with the labels that each got.

#253 Add missing xip.io docs from 0.8 (I hope that last time)
  content/docs/0.8/kyma/docs/04-06-gke-xip.io-domain.md
  content/docs/0.8/kyma/docs/04-07-aks-xip.io-domain.md
Labels: area/documentation, bug

#256 Fix bug with rendering code blocks with special char "<"
  src/components/shared/ReactMarkdown/components/Code/index.tsx
  src/components/shared/ReactMarkdown/helpers.ts
  src/components/shared/ReactMarkdown/index.tsx
Labels: area/core-and-supporting, area/documentation, bug

#257 Update CODEOWNERS
  CODEOWNERS
Labels: area/community, enhancement

#254 Add release notes for 0.9 Florence release
  content/blog-posts/2019-04-08-release-notes-0.9/index.md
Labels: area/documentation

#261 Update links in the release notes
  content/blog-posts/2019-04-08-release-notes-0.9/index.md
Labels: area/documentation, quality/release

#264 Fix issues related to copy button
  package-lock.json
  src/components/shared/ReactMarkdown/components/Code/index.tsx
Labels: area/core-and-supporting, area/documentation, bug

#267 Fix broken manifest
  gatsby-config.js
  static/android-chrome-192x192.png
  static/site.webmanifest
Labels: area/community

#265 Add Arithnea logo to Early Adopters section
  src/components/landingPage/EarlyAdopters.tsx
  src/components/landingPage/EarlyAdopters/EarlyAdopters.tsx
  src/components/landingPage/EarlyAdopters/EarlyAdoptersListItem.tsx
  src/components/landingPage/LandingPage.tsx
  src/components/landingPage/Sprites.tsx
  src/components/landingPage/styled.ts
Labels: area/community, area/core-and-supporting

#271 Fix broken link
  docs/write-blog-posts.md
Labels: area/documentation

#259 Fetch documentation from kyma repository on building time website
  Makefile
  scripts/prepare-content.sh
  scripts/publish-website.sh
  tools/content-loader/.eslinterrc
  tools/content-loader/.prettierignore
  tools/content-loader/.prettierrc
  tools/content-loader/Dockerfile
  tools/content-loader/Makefile
  tools/content-loader/README.md
  tools/content-loader/bin/main.ts
  tools/content-loader/package-lock.json
  tools/content-loader/package.json
  tools/content-loader/src/config.ts
  tools/content-loader/src/documentation/checking.js
  tools/content-loader/src/documentation/config.js
  tools/content-loader/src/documentation/copy.js
  tools/content-loader/src/documentation/docsBranches.js
  tools/content-loader/src/documentation/generateDocsVersions.js
  tools/content-loader/src/documentation/index.js
  tools/content-loader/src/github-client/git-client.ts
  tools/content-loader/src/github-client/github-client.ts
  tools/content-loader/src/helpers/gitClient.js
  tools/content-loader/src/helpers/githubClient.js
  tools/content-loader/src/index.js
  tools/content-loader/src/prepare-docs/branches-checking.ts
  tools/content-loader/src/prepare-docs/branches-serializer.ts
  tools/content-loader/src/prepare-docs/config.ts
  tools/content-loader/src/prepare-docs/copy-docs.ts
  tools/content-loader/src/prepare-docs/docs-versions.ts
  tools/content-loader/src/prepare-docs/index.ts
  tools/content-loader/src/prepare-docs/release-fetcher.ts
  tools/content-loader/src/prepare-docs/tag-fetcher.ts
  tools/content-loader/tsconfig.json
Labels: area/core-and-supporting, area/documentation, enhancement

#273 Update image of content-loader-tool
  Makefile
  scripts/prepare-content.sh
Labels: area/core-and-supporting, area/documentation, enhancement

#269 Release Notes 1.0
  content/blog-posts/2019-04-25-release-notes-1.0/index.md
Labels: area/documentation

#274 Create new target in Makefile
  Makefile
Labels: area/ci, enhancement
