Repository kyma-project/website, pull requests merged in 2019-08, with the labels that each got.

#405 Fix dead link
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
Labels: area/documentation

#404 Fixed typo
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
Labels: area/documentation

#406 Fix language in birthday blogpost
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
Labels: area/documentation

#408 Fix links
  .github/pull-request-template.md
  content/blog-posts/2018-12-03-kyma-at-kubecon/index.md
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
  content/blog-posts/2019-02-20-core-sig/index.md
  content/blog-posts/2019-05-20-transparency-through-roadmap/index.md
  docs/write-blog-posts.md
Labels: area/documentation

#411 Extend the banner end date
  content/banner/slides.yml
Labels: area/documentation

#407 Prepare content-loader tool for community view
  .gitignore
  .prettierignore
  gatsby/pages/roadmap/modalPage.ts
  netlify/functions/utils/github-client.ts
  package-lock.json
  package.json
  src/common/i18n/injectIntl.tsx
  tools/content-loader/.gitignore
  tools/content-loader/.prettierignore
  tools/content-loader/.prettierrc
  tools/content-loader/README.md
  tools/content-loader/bin/main.ts
  tools/content-loader/package.json
  tools/content-loader/src/cdt-serializer/index.ts
  tools/content-loader/src/cdt-serializer/types.ts
  tools/content-loader/src/github-client/git-client.ts
  tools/content-loader/src/helpers/get-files-paths.ts
  tools/content-loader/src/prepare-community/config.ts
  tools/content-loader/src/prepare-community/copy-community.ts
  tools/content-loader/src/prepare-community/index.ts
  tools/content-loader/src/prepare-docs/copy-docs.ts
  tools/content-loader/src/prepare-roadmap/capabilities-fetcher.ts
  tools/content-loader/src/prepare-roadmap/config.ts
  tools/content-loader/src/prepare-roadmap/index.ts
  tools/content-loader/src/prepare-roadmap/tickets-extractor.ts
  tools/content-loader/src/prepare-roadmap/tickets-fetcher.ts
  tools/content-loader/src/prepare-roadmap/types.ts
Labels: area/core-and-supporting, area/documentation, enhancement

#410 Optimize site by browser-api and ssr-api
  gatsby/browser-api/index.ts
  gatsby/browser-api/wrapPageElement.tsx
  gatsby/browser-api/wrapRootElement.tsx
  gatsby/ssr-api/index.ts
  gatsby/ssr-api/wrapPageElement.tsx
  gatsby/ssr-api/wrapRootElement.tsx
  package-lock.json
  package.json
  src/common/i18n/index.ts
  src/components/landingPage/WhatIs.tsx
  src/layouts/default/components/CookiesBanner.tsx
  src/layouts/default/components/Footer.tsx
  src/layouts/default/components/Header.tsx
  src/layouts/default/components/Navigation.tsx
  src/layouts/default/components/Search/Input.tsx
  src/layouts/default/components/Search/index.tsx
  src/layouts/default/components/Search/styled.ts
  src/layouts/default/components/SlidesBanner/CircleIndicator.tsx
  src/layouts/default/components/SlidesBanner/SlideContent.tsx
  src/layouts/default/components/SlidesBanner/index.tsx
  src/layouts/default/components/SlidesBanner/styled.ts
  src/layouts/default/components/SlidesBanner/types.ts
  src/layouts/default/components/assets/LogoFirst.tsx
  src/layouts/default/components/assets/LogoSecond.tsx
  src/layouts/default/components/styled.ts
  src/layouts/default/index.tsx
  src/layouts/default/styled.ts
  src/layouts/documentation/index.tsx
  src/layouts/index.ts
  src/layouts/layoutsWrapper/index.tsx
  src/root/components/Popup.tsx
  src/root/components/index.ts
  src/root/index.tsx
  src/root/services/index.ts
  src/root/services/root.ts
  src/sitemetadata/Facebook.tsx
  src/sitemetadata/SiteMetadata.tsx
  src/sitemetadata/StructureData.tsx
  src/sitemetadata/Twitter.tsx
  src/sitemetadata/extractor/blog.ts
  src/sitemetadata/extractor/docs.ts
  src/sitemetadata/extractor/index.ts
  src/sitemetadata/extractor/roadmap.ts
  src/sitemetadata/index.tsx
  src/views/community/index.tsx
  src/views/docs/components/index.ts
  src/views/docs/components/versionSwitcher/index.tsx
  src/views/docs/components/versionSwitcher/styled.ts
  src/views/docs/index.tsx
  src/views/docs/styled.ts
Labels: area/core-and-supporting, enhancement, quality/performance

#415 Fix bug with fetching service-catalog in 1.2 and 1.3 version docs
  src/sitemetadata/SiteMetadata.tsx
  tools/content-loader/src/cdt-serializer/index.ts
  tools/content-loader/src/prepare-community/copy-community.ts
  tools/content-loader/src/prepare-docs/copy-docs.ts
Labels: area/documentation, bug

#416 Add overview tag in one of blog posts
  content/blog-posts/2019-02-18-release-0.8-plan/index.md
  content/blog-posts/2019-03-15-release-0.9-plan/index.md
  content/blog-posts/2019-04-18-release-1.0-plan/index.md
  content/blog-posts/2019-07-24-kyma-and-knative-turning-one/index.md
Labels: area/community, area/documentation, bug

#418 Fix tabs and copy button
  src/components/generic-documentation/render-engines/markdown/headers-toc/HeadersComponent.tsx
  src/components/generic-documentation/services/GenericDocs.service.ts
  src/components/shared/Tabs/styled.ts
Labels: bug

#417 Add the 1.4 release notes
  content/blog-posts/2019-08-08-release-notes-1.4/index.md
  content/blog-posts/2019-08-08-release-notes-1.4/kiali-console-ui.png
  content/blog-posts/2019-08-08-release-notes-1.4/markdown-spec.png
  content/blog-posts/2019-08-08-release-notes-1.4/namespace-settings.png
  content/blog-posts/2019-08-08-release-notes-1.4/odata-spec.png
  content/blog-posts/2019-08-08-release-notes-1.4/openAPI-spec.png
Labels: area/documentation

#420 Fix fetched number of releases in content-loader tool
  .gitignore
  tools/content-loader/src/github-client/github-client.ts
Labels: area/documentation, bug

#421 Fix link
  content/blog-posts/2019-04-08-release-notes-0.9/index.md
Labels: area/documentation

#424 Fix z-index of search results
  netlify/functions/master-build/pull-request.event.ts
  src/layouts/default/components/Search/styled.ts
Labels: bug

#426 Fix render inlineCodes in header
  src/components/generic-documentation/external/removeMarkdownSyntax.ts
  src/components/generic-documentation/render-engines/markdown/custom-renderers/Heading.tsx
  src/components/generic-documentation/renderers/styled.ts
Labels: bug

#425 Add svg optimization plugin
  .gitattributes
  gatsby/config-api/plugins.ts
  package-lock.json
  package.json
Labels: area/core-and-supporting, area/documentation, enhancement

#428 Update codeowners file
  CODEOWNERS
Labels: area/documentation

#429 Remove gatsby-plugin-optimize-svgs plugin
  gatsby/config-api/plugins.ts
  package-lock.json
  package.json
Labels: bug

#430 Update roadmap page description because of grammar
  content/i18n/en/roadmap.json
Labels: area/community, enhancement
