Repository kyma-project/website, pull requests merged in 2019-10, with the labels that each got.

#449 Fix cropped thumbnail on Facebook
  gatsby/config-api/rss-feed.ts
  gatsby/config-api/sitemetadata.ts
  gatsby/node-api/pages/community/index.ts
  package-lock.json
  package.json
  src/sitemetadata/Facebook.tsx
  src/sitemetadata/SiteMetadata.tsx
  static/facebookLogo.png
Labels: area/community

#456 #4239 Add support for new source types
  .prettierignore
  package-lock.json
  package.json
  tools/content-loader/package-lock.json
  tools/content-loader/package.json
  tools/content-loader/src/cdt-serializer/index.ts
  tools/content-loader/src/cdt-serializer/types.ts
  tools/content-loader/src/helpers/download-resource.ts
  tools/content-loader/src/helpers/helm-tpl-value-resolver.ts
  tools/content-loader/src/helpers/helm-tpl-value-resolver.unit.test.ts
  tools/content-loader/src/helpers/index.ts
  tools/content-loader/src/helpers/memoize-read.ts
  tools/content-loader/src/helpers/memoize-read.unit.test.ts
  tools/content-loader/src/helpers/parent-dir.ts
  tools/content-loader/src/helpers/parent-dir.unit.test.ts
  tools/content-loader/src/helpers/read-file.ts
  tools/content-loader/src/helpers/read-yaml.ts
  tools/content-loader/tsconfig.json
Labels: area/application-connector, area/core-and-supporting, area/documentation, enhancement

#460 Add robots txt
  gatsby/config-api/plugins.ts
  package-lock.json
  package.json
Labels: area/community, area/core-and-supporting, enhancement, hacktoberfest

#463 Fix bug with overflow on x axis of model container in OpenAPI component.
  package-lock.json
  src/components/generic-documentation/render-engines/openapi/StyledOpenApi.ts
Labels: area/core-and-supporting, area/documentation, bug, enhancement

#467 Move all dependencies from tools to root
  Makefile
  package-lock.json
  package.json
  tools/content-loader/Makefile
  tools/content-loader/package-lock.json
  tools/content-loader/package.json
  tools/content-loader/src/github-client/github-client.ts
  tools/content-loader/src/github-client/github-graphql-client.ts
Labels: enhancement

#469 Fix link
  content/blog-posts/2019-07-12-release-notes-1.3/index.md
Labels: area/documentation

#453 Add github star and fork buttons
  src/layouts/default/components/GithubButtons.tsx
  src/layouts/default/components/Header.tsx
  src/layouts/default/components/Navigation.tsx
  src/layouts/default/components/styled.ts
Labels: area/community, area/core-and-supporting, enhancement

#468 Update Readme.md of project and project structure in /docs folder
  README.md
  docs/project-structure.md
Labels: area/documentation, enhancement

#450 Add Release Notes for 1.6
  content/blog-posts/2019-10-18-release-notes-1.6/collapsible-sections.png
  content/blog-posts/2019-10-18-release-notes-1.6/grafana-dashboard.png
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
  content/blog-posts/2019-10-18-release-notes-1.6/logging-ui-lambda-view.png
  content/blog-posts/2019-10-18-release-notes-1.6/logging-ui-main.png
Labels: area/documentation

#454 Write instruction how to add case study
  .github/ISSUE_TEMPLATE/new-user-request.md
  docs/README.md
  docs/add-user.md
  docs/banner-modification.md
  docs/internationalization.md
  docs/write-blog-posts.md
Labels: area/community, area/documentation

#466 Add "Used by" section on landing page
  .github/ISSUE_TEMPLATE/new-user-request.md
  .gitignore
  config.json
  content/adopters/adopters.yaml
  content/adopters/logos/netconomy.svg
  content/adopters/logos/sap.svg
  content/early-adopters/early-adopters.yml
  content/i18n/en/landing-page.json
  gatsby/constants.ts
  gatsby/node-api/pages/index.ts
  gatsby/node-api/pages/landingPage/helpers.ts
  gatsby/node-api/pages/landingPage/index.ts
  package-lock.json
  package.json
  src/common/icons.ts
  src/types/landingPage.ts
  src/views/landingPage/Adopters/AdoptersGallery.tsx
  src/views/landingPage/Adopters/AdoptersItem.tsx
  src/views/landingPage/Adopters/index.tsx
  src/views/landingPage/Adopters/styled.ts
  src/views/landingPage/EarlyAdopters/EarlyAdoptersListItem.tsx
  src/views/landingPage/EarlyAdopters/Sprites.tsx
  src/views/landingPage/EarlyAdopters/index.tsx
  src/views/landingPage/EarlyAdopters/styled.ts
  src/views/landingPage/index.tsx
Labels: area/community, area/core-and-supporting, area/documentation, enhancement

#483 Update TSLint rules
  gatsby/browser-api/shouldUpdateScroll.ts
  gatsby/node-api/pages/community/index.ts
  gatsby/node-api/pages/docs/modalPage.ts
  gatsby/node-api/pages/utils/createIntlPage.ts
  package-lock.json
  package.json
  src/common/utils/scrollToAnchor.ts
  src/components/generic-documentation/render-engines/markdown/helpers/postProcessingHeaders.ts
  src/components/generic-documentation/serializer/index.ts
  src/components/shared/Icon/index.tsx
  src/components/shared/ReactMarkdown/components/Code/index.tsx
  src/components/shared/ReactMarkdown/components/EmbedVideo/helpers.ts
  src/components/shared/ReactMarkdown/index.tsx
  src/components/shared/ReactMarkdown/parseHTML/Tabs.tsx
  src/layouts/default/components/SlidesBanner/index.tsx
  src/views/blog/components/content/PostContent.tsx
  src/views/blog/root/index.tsx
  tsconfig.json
  tslint.json
Labels: area/core-and-supporting, enhancement

#470 Add newsroom section on landingPage
  config.json
  content/i18n/en/landing-page.json
  gatsby/node-api/pages/blog/helpers.ts
  gatsby/node-api/pages/index.ts
  gatsby/node-api/pages/landingPage/index.ts
  package-lock.json
  package.json
  src/custom.d.ts
  src/layouts/default/components/Footer.tsx
  src/types/landingPage.ts
  src/views/landingPage/Adopters/AdoptersGallery.tsx
  src/views/landingPage/Adopters/styled.ts
  src/views/landingPage/Community/index.tsx
  src/views/landingPage/Community/styled.ts
  src/views/landingPage/KeyFeatures/index.tsx
  src/views/landingPage/KeyFeatures/styled.ts
  src/views/landingPage/Newsroom/Card.tsx
  src/views/landingPage/Newsroom/LastBlogPosts.tsx
  src/views/landingPage/Newsroom/TwitterFrame.tsx
  src/views/landingPage/Newsroom/YouTubeFrame.tsx
  src/views/landingPage/Newsroom/index.tsx
  src/views/landingPage/Newsroom/styled.ts
  src/views/landingPage/index.tsx
Labels: area/community, area/core-and-supporting, enhancement

#485 Add Accenture to Used by section
  content/adopters/adopters.yaml
  content/adopters/logos/accenture.svg
Labels: area/community, enhancement

#484 Add 1.7 release notes
  content/blog-posts/2019-10-30-release-notes-1.7/details-view.png
  content/blog-posts/2019-10-30-release-notes-1.7/index.md
Labels: area/documentation
