Repository kyma-project/website, pull requests merged in 2019-01, with the labels that each got.

#170 Fix styling headers after merging chains enhancement
  static/global.css
Labels: area/community, area/documentation, bug

#171 Update gatsby packages for render html tags in excerpt in blog posts
  package-lock.json
  package.json
  src/blog-posts/5-release-notes-041.md
  src/blog-posts/7-release-notes-05.md
  src/components/blog/PostFooter.js
  src/components/content/MDContent.js
Labels: bug

#173 Fix the documentation generation
  Makefile
  package-lock.json
  scripts/generate-docs.sh
  scripts/helpers/git-config.sh
  scripts/prepare-website.sh
  src/api-extensions/documentation-pages.js
  src/components/docs/DocsContent/DocsProcessor.js
  src/components/docs/navigation/VersionSwitcher.js
  src/locales/en/UI.json
  static/documentation/config.json
  tools/documentation-generator/README.md
  tools/documentation-generator/src/config.js
  tools/documentation-generator/src/generators/configuration.js
  tools/documentation-generator/src/helpers/github.js
  tools/documentation-generator/src/helpers/release.js
  tools/documentation-generator/src/index.js
Labels: area/community, area/documentation, bug

#174 Bump generator image
  scripts/generate-docs.sh
Labels: area/community

#175 Change git user identity
  Makefile
Labels: area/community, bug

#176 Add scrollSpy on docs content
  src/api-extensions/documentation-pages.js
  src/api-extensions/links-parser.js
  src/components/blog/Post.js
  src/components/docs/DocsContent/DocsContent.component.js
  src/components/docs/DocsContent/DocsContent.container.js
  src/components/docs/DocsContent/DocsProcessor.js
  src/components/docs/DocsRoot.component.js
  src/components/docs/MainPage/MainPage.js
  src/components/docs/MainPage/styled.js
  src/components/docs/Navigation/LeftNavigation/BackToTop/BackToTop.js
  src/components/docs/Navigation/LeftNavigation/LeftNavigation.js
  src/components/docs/Navigation/LeftNavigation/NavigationList/NavigationGroup.js
  src/components/docs/Navigation/LeftNavigation/NavigationList/NavigationList.js
  src/components/docs/Navigation/LeftNavigation/NavigationList/NavigationSections.js
  src/components/docs/Navigation/LeftNavigation/NavigationList/styled.js
  src/components/docs/Navigation/LeftNavigation/VersionSwitcher/VersionSwitcher.js
  src/components/docs/Navigation/LeftNavigation/VersionSwitcher/styled.js
  src/components/docs/Navigation/LeftNavigation/styled.js
  src/components/docs/Navigation/RightNavigation/RightNavigation.js
  src/components/docs/Navigation/ScrollSpy/ScrollSpy.js
  src/components/docs/Navigation/assets/docs-icon.svg
  src/components/docs/external/Navigation/NavigationList.component.js
  src/components/docs/navigation/VersionSwitcher.js
  src/components/landing/Community.js
  src/components/landing/Features.js
  src/constants/chainData.js
  src/constants/docs.js
  src/helpers/tokenize.js
  src/locales/en/UI.json
  static/global.css
Labels: area/documentation, enhancement

#182 Correct dead links
  src/blog-posts/11-release-notes-06.md
Labels: area/documentation

#185 Change wording
  src/blog-posts/11-release-notes-06.md
Labels: area/documentation
