Repository kyma-project/website, pull requests merged in 2019-12, with the labels that each got.

#499 Add Digital Lights logo
  content/adopters/adopters.yaml
  content/adopters/logos/digital_lights.svg
  docs/add-user.md
  package-lock.json
  package.json
  src/types/landingPage.ts
  src/views/landingPage/Adopters/AdoptersItem.tsx
  src/views/landingPage/Adopters/styled.ts
Labels: area/core-and-supporting, enhancement

#503 Add migration guide link to Release Notes 1.8
  content/blog-posts/2019-11-29-release-notes-1.8/index.md
Labels: area/documentation, area/monitoring

#505 Move the migration guide information
  content/blog-posts/2019-11-29-release-notes-1.8/index.md
Labels: area/documentation

#502 Adjust temporary Rafter types in content-loader-tools
  tools/content-loader/src/cdt-serializer/index.ts
  tools/content-loader/src/cdt-serializer/types.ts
Labels: area/core-and-supporting, enhancement

#510 Fix regex for searching ClusterAssetGroup
  gatsby/node-api/pages/roadmap/helpers.ts
  package-lock.json
  package.json
  src/common/i18n/FormattedMessage.tsx
  src/common/styled/media.ts
  src/components/generic-documentation/index.tsx
  src/components/generic-documentation/render-engines/markdown/headers-toc/HeadersComponent.tsx
  src/components/shared/Link/index.tsx
  src/components/shared/ReactMarkdown/components/Heading.tsx
  src/components/shared/ReactMarkdown/index.tsx
  src/layouts/default/index.tsx
  src/modals/docs-specification/index.tsx
  src/sitemetadata/SiteMetadata.tsx
  src/views/community/index.tsx
  src/views/docs/index.tsx
  src/views/landingPage/Adopters/AdoptersGallery.tsx
  src/views/landingPage/Adopters/AdoptersItem.tsx
  src/views/landingPage/index.tsx
  static/js/docsearch.min.js
  tools/content-loader/src/cdt-serializer/index.ts
Labels: area/core-and-supporting, bug

#508 Add a blog post about Netconomy use cases
  content/blog-posts/2019-12-20-netconomy-use-case/index.md
  content/blog-posts/2019-12-20-netconomy-use-case/suggest_kyma.png
Labels: area/community

#511 Correct dead links
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
  content/blog-posts/2019-10-30-release-notes-1.7/index.md
  content/blog-posts/2019-11-29-release-notes-1.8/index.md
Labels: area/documentation

#513 Fix dead links
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
Labels: area/documentation

#509 Update the Content loader README
  tools/content-loader/README.md
Labels: area/documentation

#516 Fix sort release by using natural sorting
  src/views/roadmap/Tickets/TicketsProcessor.ts
  src/views/roadmap/Tickets/TicketsProcessor.unit.test.ts
Labels: area/community, bug

#518 Fix headers navigation
  src/components/generic-documentation/render-engines/markdown/custom-renderers/Heading.tsx
Labels: area/documentation, bug

#519 Support only last 3 releases
  package-lock.json
  package.json
  scripts/prepare-content.sh
  tools/content-loader/README.md
  tools/content-loader/src/github-client/github-client.ts
  tools/content-loader/src/prepare-docs/branches-checking.ts
  tools/content-loader/src/prepare-docs/config.ts
  tools/content-loader/src/prepare-docs/copy-docs.ts
  tools/content-loader/src/prepare-docs/docs-versions.ts
  tools/content-loader/src/prepare-docs/index.ts
  tools/content-loader/src/prepare-docs/release-fetcher.test.ts
  tools/content-loader/src/prepare-docs/release-fetcher.ts
Labels: area/documentation, enhancement

#521 Fix dead links
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
  content/blog-posts/2019-10-30-release-notes-1.7/index.md
  content/blog-posts/2019-11-29-release-notes-1.8/index.md
Labels: area/documentation, bug

#522 Update dead link
  content/blog-posts/2019-07-08-extend-wordpress/index.md
Labels: area/documentation
