Repository kyma-project/website, pull requests merged in 2019-09, with the labels that each got.

#434 Add OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: area/community, enhancement

#435 Fix typo in Release Notes 1.4
  content/blog-posts/2019-08-08-release-notes-1.4/index.md
Labels: area/documentation

#433 Add 1.5 release notes
  content/blog-posts/2019-09-09-release-notes-1.5/addons-configuration.png
  content/blog-posts/2019-09-09-release-notes-1.5/index.md
Labels: area/documentation

#440 Use @rooks/use-timeout package instead of rooks.
  package-lock.json
  package.json
  src/common/state/usePopup.ts
Labels: enhancement

#441 Fix event banner types and update related docs.
  docs/banner-modification.md
  src/layouts/default/components/SlidesBanner/SlideContent.tsx
  src/layouts/default/components/SlidesBanner/index.tsx
  src/layouts/default/components/SlidesBanner/types.ts
Labels: bug

#444 Add some improvements related to documentation view
  content/docs/master/kyma/docs/04-02-local-installation.md
  content/docs/master/kyma/docs/04-03-cluster-installation.md
  content/docs/master/kyma/docs/04-04-marketplace-installation.md
  content/docs/master/kyma/docs/04-05-use-your-own-domain.md
  content/docs/master/kyma/docs/04-06-use-your-own-image.md
  package-lock.json
  package.json
  plugins/gatsby-plugin-anchor-behavior/gatsby-browser.js
  src/common/constants.ts
  src/common/hooks/useScrollPosition.ts
  src/common/hooks/useToggle.ts
  src/common/styled/media.ts
  src/common/utils/toKebabCase.ts
  src/components/generic-documentation/layouts/Docs.tsx
  src/components/generic-documentation/layouts/styled.ts
  src/components/generic-documentation/render-engines/markdown/custom-renderers/Heading.tsx
  src/components/generic-documentation/render-engines/markdown/custom-renderers/Link.tsx
  src/components/generic-documentation/render-engines/markdown/headers-toc/HeadersComponent.tsx
  src/components/generic-documentation/render-engines/markdown/headers-toc/RenderedHeader.tsx
  src/components/generic-documentation/render-engines/markdown/headers-toc/styled.ts
  src/components/generic-documentation/render-engines/markdown/helpers/index.ts
  src/components/generic-documentation/render-engines/markdown/helpers/scrollSpyCallback.ts
  src/components/generic-documentation/render-engines/markdown/navigation/index.tsx
  src/components/generic-documentation/render-engines/markdown/navigation/styled.ts
  src/components/generic-documentation/render-engines/markdown/plugins/tabs/parserPlugin.tsx
  src/components/generic-documentation/services/GenericDocs.service.ts
  src/components/generic-documentation/services/TabState.service.ts
  src/components/layout/Search/Input.tsx
  src/components/roadmap/Dropdown/Dropdown.tsx
  src/components/shared/ReactMarkdown/parseHTML/Tabs.tsx
  src/components/shared/Tabs/Tab.tsx
  src/components/shared/Tabs/index.tsx
  src/components/shared/Tabs/styled.ts
  src/layouts/default/components/BackToTop.tsx
  src/layouts/default/components/Header.tsx
  src/layouts/default/components/Navigation.tsx
  src/layouts/default/components/Search/Input.tsx
  src/layouts/default/components/Search/index.tsx
  src/layouts/default/components/Search/styled.ts
  src/layouts/default/components/styled.ts
  src/layouts/default/index.tsx
  src/layouts/documentation/index.tsx
  src/root/services/root.ts
  src/views/docs/components/versionSwitcher/styled.ts
  src/views/docs/index.tsx
  src/window.d.ts
Labels: area/core-and-supporting, area/documentation, enhancement

#445 Fix link
  content/blog-posts/2019-06-13-release-notes-1.2/index.md
Labels: area/documentation
