Repository kyma-project/website, pull requests merged in 2020-08, with the labels that each got.

#599 Add release notes for 1.14 Ulm
  content/blog-posts/2020-08-06-release-notes-1.14/APIRules.png
  content/blog-posts/2020-08-06-release-notes-1.14/details-view.png
  content/blog-posts/2020-08-06-release-notes-1.14/index.md
  content/blog-posts/2020-08-06-release-notes-1.14/message-toast.png
  content/blog-posts/2020-08-06-release-notes-1.14/runtime-provisioner-dashboard.png
Labels: area/documentation

#612 Correct the intro
  content/blog-posts/2020-08-06-release-notes-1.14/index.md
Labels: area/documentation

#613 Fix broken and outdated links in Release Notes for Kyma 1.7 and 1.11
  content/blog-posts/2019-10-30-release-notes-1.7/index.md
  content/blog-posts/2020-03-31-release-notes-1.11/index.md
Labels: area/documentation, bug

#616 Fix clearing cache in Netlify.
  Makefile
  tools/content-loader/Makefile
Labels: area/documentation, enhancement

#618 Fix broken links in release notes
  content/blog-posts/2020-05-08-release-notes-1.12/index.md
Labels: area/documentation
