Repository kyma-project/website, pull requests merged in 2020-09, with the labels that each got.

#623 Add the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, enhancement

#626 Fix little bugs
  src/components/generic-documentation/render-engines/markdown/navigation/index.tsx
  src/components/generic-documentation/renderers/styled.ts
Labels: area/documentation, bug

#620 Prepare Manifesto and Key features sections for website
  content/i18n/en/landing-page.json
  src/common/i18n/flattenMessages.ts
  src/common/i18n/injectIntl.tsx
  src/common/i18n/types.ts
  src/common/icons.ts
  src/components/shared/Link/index.tsx
  src/styles/css/fonts.css
  src/styles/font/Poppins-Regular.otf
  src/types/landingPage.ts
  src/views/landingPage/Features/FeatureCard/index.tsx
  src/views/landingPage/Features/FeatureCard/styled.ts
  src/views/landingPage/Features/Header/index.tsx
  src/views/landingPage/Features/Header/styled.ts
  src/views/landingPage/Features/index.tsx
  src/views/landingPage/Manifesto/index.tsx
  src/views/landingPage/Manifesto/styled.ts
  src/views/landingPage/assets/landing-page/features/extensibility.svg
  src/views/landingPage/assets/landing-page/features/runtime.svg
  src/views/landingPage/assets/landing-page/features/support.svg
Labels: area/community, enhancement

#633 Fix broken natss link
  content/blog-posts/2020-05-29-release-notes-1.13/index.md
Labels: area/documentation

#636 Show latest cli docs versions
  config.json
Labels: enhancement
