Repository kyma-project/website, pull requests merged in 2020-05, with the labels that each got.

#565 Fix ownership of the content folder and its subfolders
  CODEOWNERS
Labels: area/documentation

#556 Add Release Notes 1.12 Santiago
  content/blog-posts/2020-05-08-release-notes-1.12/api-packages.png
  content/blog-posts/2020-05-08-release-notes-1.12/diff.png
  content/blog-posts/2020-05-08-release-notes-1.12/functions-view.png
  content/blog-posts/2020-05-08-release-notes-1.12/index.md
  content/blog-posts/2020-05-08-release-notes-1.12/resources-and-replicas.png
Labels: area/documentation

#568 Change Serverless screens in Release Notes
  content/blog-posts/2020-05-08-release-notes-1.12/diff.png
  content/blog-posts/2020-05-08-release-notes-1.12/functions-view.png
  content/blog-posts/2020-05-08-release-notes-1.12/resources-and-replicas.png
Labels: area/community, area/documentation

#569 Add border to the screenshot
  content/blog-posts/2020-05-08-release-notes-1.12/functions-view.png
Labels: area/community, area/documentation

#571 Fix dead links in release notes
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
  content/blog-posts/2020-01-09-release-notes-1.9/index.md
Labels: area/documentation

#570 Add new banner
  content/banner/slides.yml
Labels: area/community, area/core-and-supporting

#572 Fix broken link in RN
  content/blog-posts/2020-05-08-release-notes-1.12/index.md
Labels: area/documentation

#579 added no_follow to netflix
  src/layouts/default/components/Footer.tsx
Labels: area/community, enhancement

#573 Create a blog post describing the Kyma website
  content/blog-posts/2020-05-19-kyma-website/ClusterAssetGroups.png
  content/blog-posts/2020-05-19-kyma-website/building-process.svg
  content/blog-posts/2020-05-19-kyma-website/documentation-component.png
  content/blog-posts/2020-05-19-kyma-website/index.md
  content/blog-posts/2020-05-19-kyma-website/issue-labels.png
  content/blog-posts/2020-05-19-kyma-website/left-side-navigation.png
  content/blog-posts/2020-05-19-kyma-website/react-markdown.png
  content/blog-posts/2020-05-19-kyma-website/release-switcher.png
  content/blog-posts/2020-05-19-kyma-website/successful-preview.png
  content/blog-posts/2020-05-19-kyma-website/views.png
Labels: area/community, area/documentation

#587 Fix history back action on docs and community views
  src/components/generic-documentation/render-engines/markdown/helpers/scrollSpyCallback.ts
Labels: area/community, area/documentation, bug

#588 Remove dead link to Istio documentation
  content/blog-posts/2019-07-31-kyma-collaboration-with-ory/index.md
Labels: area/documentation, bug

#582 Create 1.13 release notes
  content/blog-posts/2020-05-29-release-notes-1.13/index.md
Labels: area/documentation
