Repository kyma-project/website, pull requests merged in 2020-01, with the labels that each got.

#524 Fix dead links to compass docs
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
  content/blog-posts/2019-10-30-release-notes-1.7/index.md
Labels: area/documentation

#527 Fix gathering values for templates in yaml files
  tools/content-loader/src/cdt-serializer/index.ts
  tools/content-loader/src/helpers/helm-tpl-value-resolver.ts
  tools/content-loader/src/prepare-docs/copy-docs.ts
Labels: area/core-and-supporting, bug

#514 Add 1.9 release notes
  content/blog-posts/2020-01-09-release-notes-1.9/index.md
  content/blog-posts/2020-01-09-release-notes-1.9/list-views-in-compass-UI.png
  content/blog-posts/2020-01-09-release-notes-1.9/status-info.png
  src/components/shared/NotePanel/styled.ts
Labels: WIP, area/documentation

#528 Remove links to releases not on the website
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
Labels: area/documentation

#529 Add missing sections to release notes
  content/blog-posts/2020-01-09-release-notes-1.9/index.md
Labels: area/documentation, area/installation

#526 Add blog post on integration testing in Kyma
  content/blog-posts/2020-01-16-integration-testing-in-k8s/index.md
  content/blog-posts/2020-01-16-integration-testing-in-k8s/test-status.png
Labels: area/documentation

#532 Fix a typo in the blog post
  content/blog-posts/2020-01-16-integration-testing-in-k8s/index.md
Labels: area/documentation

#533 Minor blog post improvements
  content/blog-posts/2020-01-16-integration-testing-in-k8s/index.md
Labels: area/documentation

#534 Add subtle tweaks and polishes to the latest post
  content/blog-posts/2020-01-16-integration-testing-in-k8s/index.md
Labels: area/documentation

#535 Enable stale bot for epics
  .github/stale.yml
Labels: area/community
