Repository kyma-project/website, pull requests merged in 2020-07, with the labels that each got.

#600 Pearl Group Adopter
  content/adopters/adopters.yaml
  content/adopters/logos/pearlgroup.svg
Labels: area/community

#602 Fix a broken link
  content/blog-posts/2020-05-08-release-notes-1.12/index.md
Labels: area/documentation, bug

#607 Fix broken link
  content/blog-posts/2020-05-29-release-notes-1.13/index.md
Labels: area/documentation
