Repository kyma-project/website, pull requests merged in 2020-10, with the labels that each got.

#644 Modified Code Owners
  CODEOWNERS
Labels: area/community

#645 Add the link to AsyncAPI rendering sandbox in Release Notes for Kyma 0.6 to ignored in milv
  milv.config.yaml
Labels: area/documentation, bug, hacktoberfest

#646 Add encoding dependency
  Makefile
  package-lock.json
  package.json
Labels: bug

#643 Removing softicious
  content/adopters/adopters.yaml
  content/adopters/logos/softicious.svg
Labels: area/community, bug
