Repository kyma-project/website, pull requests merged in 2020-06, with the labels that each got.

#564 Improve SEO and Accessibility metrics
  .github/ISSUE_TEMPLATE/new-user-request.md
  content/adopters/adopters.yaml
  content/i18n/en/landing-page.json
  content/i18n/en/layout.json
  docs/add-user.md
  gatsby-ssr.ts
  gatsby/config-api/plugins.ts
  gatsby/ssr-api/index.ts
  gatsby/ssr-api/onRenderBody.tsx
  package-lock.json
  package.json
  src/components/shared/Button/index.tsx
  src/components/shared/Link/index.tsx
  src/layouts/default/components/GithubButtons.tsx
  src/layouts/default/components/Header.tsx
  src/layouts/default/components/Navigation.tsx
  src/layouts/default/components/Search/Input.tsx
  src/layouts/default/components/Search/index.tsx
  src/layouts/default/components/assets/LogoFirst.tsx
  src/layouts/default/components/assets/LogoSecond.tsx
  src/types/landingPage.ts
  src/views/docs/components/versionSwitcher/index.tsx
  src/views/landingPage/Adopters/AdoptersGallery.tsx
  src/views/landingPage/Adopters/AdoptersItem.tsx
  src/views/landingPage/assets/landing-page/TechIndependent.tsx
  static/css/fonts.css
Labels: area/core-and-supporting, enhancement

#563 Lazy loading images on docs and community views
  gatsby-browser.ts
  gatsby/node-api/nodes/index.ts
  gatsby/node-api/nodes/onCreateNode/imagesSpec.tsx
  gatsby/node-api/nodes/onCreateNode/index.ts
  gatsby/node-api/pages/community/helpers.ts
  gatsby/node-api/pages/docs/helpers.ts
  gatsby/node-api/pages/utils/docs-generator/helpers.ts
  gatsby/node-api/pages/utils/docs-generator/types.ts
  gatsby/types.ts
  package-lock.json
  package.json
  src/common/styled/GlobalStyles.tsx
  src/components/generic-documentation/index.tsx
  src/components/generic-documentation/render-engines/markdown/custom-renderers/Image.tsx
  src/components/generic-documentation/render-engines/markdown/index.tsx
  src/components/generic-documentation/renderers/styled.ts
  src/components/generic-documentation/serializer/index.ts
  src/types/docs.ts
Labels: area/core-and-supporting, enhancement

#592 Uninline inlined css
  gatsby-browser.ts
  gatsby-ssr.ts
  gatsby/browser-api/wrapRootElement.tsx
  gatsby/ssr-api/index.ts
  gatsby/ssr-api/onPreRenderHTML.tsx
  src/common/styled/GlobalStyles.tsx
  src/common/styled/index.ts
  src/common/typography.ts
  src/root/index.tsx
  static/css/global.css
  static/css/typography.css
Labels: area/community, enhancement

#597 Update robots-txt generation config to be more dynamic
  gatsby/config-api/plugins.ts
  package-lock.json
  package.json
  plugins/kyma-project-robots-txt-plugin/gatsby-node.js
  plugins/kyma-project-robots-txt-plugin/package.json
Labels: enhancement

#598 Filter from sitemap old and master docs versions
  gatsby/config-api/plugins.ts
  gatsby/config-api/rss-feed.ts
  gatsby/config-api/sitemap.ts
  gatsby/node-api/pages/docs/componentPage.ts
  gatsby/node-api/pages/docs/index.ts
  gatsby/node-api/pages/index.ts
  plugins/kyma-project-robots-txt-plugin/gatsby-node.js
Labels: area/community
