Repository kyma-project/website, pull requests merged in 2021-07, with the labels that each got.

#744 Add release notes for Kyma 1.24 Ekibastuz
  content/blog-posts/2021-07-02-release-notes-1.24/index.md
Labels: area/documentation, lgtm, size/M

#748 Withdraw python 3.9 release notes
  content/blog-posts/2021-07-02-release-notes-1.24/index.md
Labels: lgtm, size/XS

#749 Fix dead link
  content/blog-posts/2018-10-18-accelerate-innovation-with-kyma/index.md
Labels: area/documentation, lgtm, size/XS

#750 Update the Istio version for the release
  content/blog-posts/2021-07-02-release-notes-1.24/index.md
Labels: area/documentation, lgtm, size/XS

#751 Fix outdated release notes links
  content/blog-posts/2021-04-08-release-notes-1.21/index.md
Labels: area/documentation, lgtm, size/S

#753 Fix dead link
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
Labels: area/documentation, lgtm, size/XS
