Repository kyma-project/website, pull requests merged in 2021-10, with the labels that each got.

#773 Add missing archive releases
  config.json
Labels: size/XS, lgtm

#774 Fixed dead links
  .github/pull-request-template.md
  content/blog-posts/2018-12-03-kyma-at-kubecon/index.md
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
  content/blog-posts/2019-05-17-release-notes-1.1/index.md
  content/blog-posts/2019-05-20-transparency-through-roadmap/index.md
  content/blog-posts/2019-07-12-release-notes-1.3/index.md
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
  content/blog-posts/2019-08-08-release-notes-1.4/index.md
  content/blog-posts/2019-09-09-release-notes-1.5/index.md
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
  content/blog-posts/2020-12-17-release-notes-1.18/index.md
  docs/write-blog-posts.md
Labels: area/documentation, size/M, lgtm

#764 Landing page with personas
  config.json
  content/i18n/en/landing-page.json
  content/i18n/en/siteMetadata.json
  src/layouts/default/components/Header.tsx
  src/views/landingPage/CheckItOut/Termynal/Termynal.tsx
  src/views/landingPage/Nutshell/index.tsx
  src/views/landingPage/assets/landing-page/checkItOut/terminal.png
  src/views/landingPage/assets/landing-page/nutshell/in-the-nutshell.png
  src/views/landingPage/index.tsx
Labels: enhancement, area/community, size/M, lgtm

#778 Fix broken links
  content/blog-posts/2018-10-10-release-notes-0.4.1/index.md
  content/blog-posts/2020-05-19-kyma-website/index.md
  content/blog-posts/2020-08-28-release-notes-1.15/index.md
  content/blog-posts/2021-04-29-release-notes-1.22/index.md
  content/blog-posts/2021-06-02-release-notes-1.23/index.md
Labels: area/documentation, size/S, lgtm

#775 Add redirect from docs to docs/kyma/latest
  static/_redirects
Labels: size/XS, lgtm

#781 Use latest 2 versions
  config.json
Labels: size/S, lgtm

#779 Add version disclaimer to kyma landing page
  config.json
  content/i18n/en/landing-page.json
  src/views/landingPage/CheckItOut/Termynal/Termynal.tsx
  src/views/landingPage/CheckItOut/index.tsx
  src/views/landingPage/CheckItOut/styled.ts
  src/views/landingPage/assets/landing-page/checkItOut/terminal.png
  src/views/landingPage/assets/landing-page/checkItOut/terminal.svg
  src/views/landingPage/index.tsx
Labels: size/L, lgtm

#782 Fix CLI installation link
  config.json
Labels: size/XS

#783 Fix used-by anchor
  src/views/landingPage/UsedBy/index.tsx
Labels: size/XS

#785 trigger build on kyma-project.io
  netlify/functions/master-build/pull-request.event.ts
Labels: size/XS, lgtm

#787 fix website links
  content/blog-posts/2019-06-13-release-notes-1.2/index.md
  content/blog-posts/2020-02-11-release-notes-1.10/index.md
Labels: area/documentation, lgtm
