Repository kyma-project/website, pull requests merged in 2021-08, with the labels that each got.

#746 Blog Post on unofficial Kyma Update Twitter Bot
  content/blog-posts/2021-06-28-unofficial-kyma-twitter-bot/index.md
Labels: size/M, lgtm

#755 Change the date of the blog post
  content/blog-posts/2021-08-06-unofficial-kyma-twitter-bot/index.md
Labels: bug, area/documentation, size/XS, lgtm

#756 Fix the typo in the blog post
  content/blog-posts/2021-08-06-unofficial-kyma-twitter-bot/index.md
Labels: bug, area/documentation, size/XS, lgtm

#757 Yet another blog post fix
  content/blog-posts/2021-08-06-unofficial-kyma-twitter-bot/index.md
Labels: bug, area/documentation, size/XS, lgtm

#759 Remove kazydek from CODEOWNERS
  CODEOWNERS
Labels: area/community, area/documentation, size/XS, lgtm

#762 Add personas component
  content/i18n/en/landing-page.json
  src/types/landingPage.ts
  src/views/landingPage/Personas/Persona/index.tsx
  src/views/landingPage/Personas/Persona/styled.tsx
  src/views/landingPage/Personas/index.tsx
  src/views/landingPage/Personas/styled.tsx
  src/views/landingPage/assets/landing-page/personas/coding.png
  src/views/landingPage/assets/landing-page/personas/effective.png
  src/views/landingPage/index.tsx
Labels: enhancement, area/community, size/L, lgtm

#765 Fix headers in 2.0 website
  Makefile
  src/components/generic-documentation/render-engines/markdown/custom-renderers/Heading.tsx
  src/components/generic-documentation/render-engines/markdown/helpers/postProcessingHeaders.ts
Labels: size/XS, lgtm
