Repository kyma-project/website, pull requests merged in 2021-05, with the labels that each got.

#717 Change master to main (leftovers)
  config.json
  content/blog-posts/2019-04-08-release-notes-0.9/index.md
  content/blog-posts/2019-06-13-release-notes-1.2/index.md
  content/blog-posts/2019-08-08-release-notes-1.4/index.md
  content/blog-posts/2019-09-09-release-notes-1.5/index.md
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
  content/blog-posts/2020-01-16-integration-testing-in-k8s/index.md
  content/blog-posts/2020-05-08-release-notes-1.12/index.md
  content/blog-posts/2020-05-19-kyma-website/index.md
  content/community/content/docs/05-links-in-docs.md
  content/community/content/docs/README.md
  content/docs/kyma/1.0/kyma/docs/04-02-local-installation.md
  content/docs/kyma/1.0/kyma/docs/04-08-custom-component-installation.md
  content/docs/kyma/1.0/kyma/docs/04-10-update.md
  content/docs/kyma/1.0/kyma/docs/08-05-installation-overrides.md
  content/docs/kyma/1.0/service-mesh/docs/03-03-istio-rbac.md
  content/docs/kyma/fix-links.json
  content/docs/kyma/master/kyma/docs/04-08-custom-component-installation.md
  content/docs/kyma/master/kyma/docs/04-10-update.md
  content/docs/kyma/master/kyma/docs/06-01-installation.md
  content/docs/kyma/master/kyma/docs/08-05-installation-overrides.md
  content/docs/kyma/master/service-mesh/docs/03-03-istio-rbac.md
  tools/content-loader/README.md
Labels: area/documentation, lgtm, size/M

#722 Update codeowners
  CODEOWNERS
Labels: area/community, lgtm, size/XS

#724 Bump lodash to 4.17.21
  package-lock.json
  package.json
Labels: lgtm, size/XXL

#725 Upgrade Wookiee beings in the CODEOWNERS file
  CODEOWNERS
  OWNERS
Labels: area/serverless, lgtm, size/XS

#726 Update landing page
  content/i18n/en/landing-page.json
  src/views/landingPage/Features/Header/index.tsx
  src/views/landingPage/Features/Header/styled.ts
  src/views/landingPage/Manifesto/index.tsx
  src/views/landingPage/Manifesto/styled.ts
  src/views/landingPage/Nutshell/index.tsx
  src/views/landingPage/Nutshell/styled.tsx
  src/views/landingPage/assets/landing-page/nutshell/in-the-nutshell.png
Labels: lgtm, size/M

#731 Fix commas, image font, wording
  content/i18n/en/landing-page.json
  src/views/landingPage/assets/landing-page/nutshell/in-the-nutshell.png
Labels: lgtm, size/XS

#732 Introducing `Check it out` component to the new landing page
  config.json
  content/i18n/en/landing-page.json
  src/views/landingPage/CheckItOut/Termynal/Termynal.tsx
  src/views/landingPage/CheckItOut/Termynal/styled.tsx
  src/views/landingPage/CheckItOut/index.tsx
  src/views/landingPage/CheckItOut/styled.ts
  src/views/landingPage/assets/landing-page/checkItOut/1.png
  src/views/landingPage/assets/landing-page/checkItOut/2.png
  src/views/landingPage/assets/landing-page/checkItOut/terminal.png
  src/views/landingPage/index.tsx
Labels: lgtm, size/L
