Repository kyma-project/website, pull requests merged in 2021-02, with the labels that each got.

#667 fix: handle links to files
  content/community/content/docs/01-content-strategy.md
  content/community/content/docs/assets/SAP Corporate Contributor License Agreement (5-26-15).pdf
  gatsby/node-api/nodes/onCreateNode/copyAssets.ts
  src/components/shared/Link/index.tsx
Labels: area/community

#670 Add Twitter links to ignored to get rid of Bad Request errors
  milv.config.yaml
Labels: area/documentation, bug

#671 Fix a dead link
  content/blog-posts/2020-08-28-release-notes-1.15/index.md
Labels: area/documentation, bug

#676 Add renamed fields to MILV config
  milv.config.yaml
Labels: area/documentation, enhancement
