Repository kyma-project/website, pull requests merged in 2021-12, with the labels that each got.

#798 Fix the broken link
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
Labels: bug, area/documentation, size/XS, lgtm

#790 Add release notes for K2.0
  content/blog-posts/2021-12-07-release-notes-2.0/index.md
Labels: area/documentation, size/L, lgtm

#805 Fix kyma 2.0.0 release tag in blog post note
  content/blog-posts/2021-12-07-release-notes-2.0/index.md
Labels: size/XS, lgtm

#808 Add release 2.0
  config.json
Labels: size/XS, lgtm

#809 Convert links in 2.0 release notes to point to the 2.0 tag
  content/blog-posts/2021-12-07-release-notes-2.0/index.md
Labels: area/documentation, size/S, lgtm

#812 Navigable search results
  src/layouts/default/components/Search/index.tsx
Labels: size/S
