Repository kyma-project/website, pull requests merged in 2021-11, with the labels that each got.

#792 fix broken links
  content/blog-posts/2018-12-03-kyma-at-kubecon/index.md
  content/blog-posts/2018-12-11-release-0.6-plan/index.md
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
  content/blog-posts/2019-02-20-core-sig/index.md
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
Labels: size/S, lgtm

#791 Update to 1.24 RN
  content/blog-posts/2021-07-02-release-notes-1.24/index.md
Labels: area/documentation, size/XS, lgtm

#793 change defintion of CRD
  content/docs/kyma/main/glossary.md
Labels: size/XS, lgtm

#795 modify config
  milv.config.yaml
Labels: size/XS, lgtm

#794 Fix the patch version for Istio update to 1.11
  content/blog-posts/2021-07-02-release-notes-1.24/index.md
Labels: area/documentation, area/security, size/XS, lgtm
