Repository kyma-project/website, pull requests merged in 2021-04, with the labels that each got.

#696 Change excluding terms into inclusive alternatives
  .github/ISSUE_TEMPLATE/new-user-request.md
  .github/pull-request-template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  content/blog-posts/2018-09-24-start-with-person-service/index.md
  content/blog-posts/2018-10-10-release-notes-0.4.1/index.md
  content/blog-posts/2018-12-03-kyma-at-kubecon/index.md
  content/blog-posts/2018-12-11-release-0.6-plan/index.md
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
  content/blog-posts/2019-01-14-release-notes-0.6/main-branch.png
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
  content/blog-posts/2019-02-20-core-sig/index.md
  content/blog-posts/2019-04-08-release-notes-0.9/index.md
  content/blog-posts/2019-05-17-release-notes-1.1/index.md
  content/blog-posts/2019-05-20-transparency-through-roadmap/index.md
  content/blog-posts/2019-07-08-extend-wordpress/index.md
  content/blog-posts/2019-07-12-release-notes-1.3/index.md
  content/blog-posts/2019-07-24-happy-birthday-kyma/index.md
  content/blog-posts/2019-07-31-kyma-collaboration-with-ory/index.md
  content/blog-posts/2019-08-08-release-notes-1.4/index.md
  content/blog-posts/2020-01-09-release-notes-1.9/index.md
  content/blog-posts/2020-01-16-integration-testing-in-k8s/index.md
  content/blog-posts/2020-03-31-release-notes-1.11/index.md
  content/blog-posts/2020-05-19-kyma-website/building-process.svg
  content/blog-posts/2020-05-19-kyma-website/index.md
  content/community/content/docs/01-content-strategy.md
  content/community/content/docs/03-documentation-toggle.md
  content/community/content/docs/06-release-notes.md
  content/community/get-started/docs/get-started.md
  content/docs/cli/master/commands/docs/kyma_install.md
  content/docs/cli/master/overview/docs/03-02-use-kyma-cli.md
  content/docs/cli/master/overview/docs/03-03-examples.md
  content/docs/kyma/1.0/kyma/docs/04-02-local-installation.md
  content/docs/kyma/1.0/kyma/docs/04-10-update.md
  content/docs/kyma/1.0/kyma/docs/06-01-installation.md
  content/docs/kyma/1.0/kyma/docs/08-01-sample-service-deployment-to-local.md
  content/docs/kyma/1.0/kyma/docs/08-02-sample-service-deployment-to-cluster.md
  content/docs/kyma/1.0/kyma/docs/08-05-installation-overrides.md
  content/docs/kyma/1.0/kyma/docs/12-01-try-out-kyma.md
  content/docs/kyma/master/kyma/docs/04-06-use-your-own-image.md
  content/docs/kyma/master/kyma/docs/04-10-update.md
  content/docs/kyma/master/kyma/docs/06-01-installation.md
  content/docs/kyma/master/kyma/docs/08-01-sample-service-deployment-to-local.md
  content/docs/kyma/master/kyma/docs/08-02-sample-service-deployment-to-cluster.md
  content/docs/kyma/master/kyma/docs/08-05-installation-overrides.md
  content/docs/kyma/master/kyma/docs/12-01-try-out-kyma.md
  docs/write-blog-posts.md
  tools/content-loader/README.md
Labels: area/documentation

#691 In a nutshell component
  content/i18n/en/landing-page.json
  package-lock.json
  src/views/landingPage/Nutshell/index.tsx
  src/views/landingPage/Nutshell/styled.tsx
  src/views/landingPage/index.tsx
Labels: WIP

#686 Create Release Notes for Kyma 1.21 Berlin
  content/blog-posts/2021-04-08-release-notes-1.21/index.md
  content/blog-posts/2021-04-08-release-notes-1.21/logs-traceId.png
Labels: area/documentation

#706 Fix the broken links
  content/blog-posts/2019-01-14-release-notes-0.6/index.md
  content/blog-posts/2020-12-17-release-notes-1.18/index.md
Labels: area/documentation, bug

#680 Install minikube so that the getting started example works directly
  src/views/landingPage/WhatIs/Termynal/Termynal.tsx
Labels: area/community

#713 Missing HTST headers
  netlify/functions/utils/github-client.ts
Labels: lgtm, size/XS

#709 Create release notes for Kyma 1.22
  content/blog-posts/2021-04-22-release-notes-1.22/index.md
Labels: area/documentation, lgtm

#715 Revert "Create release notes for Kyma 1.22"
  content/blog-posts/2021-04-22-release-notes-1.22/index.md
Labels: area/documentation, lgtm, size/M

#716 Add Kyma 1.22 release notes
  content/blog-posts/2021-04-29-release-notes-1.22/index.md
Labels: area/documentation, lgtm, size/M
