Repository kyma-project/website, pull requests merged in 2022-09, with the labels that each got.

#877 Fix broken links to Busola Migrator and Minikube 0.33.0
  content/blog-posts/2019-02-14-release-notes-0.7/index.md
  content/blog-posts/2021-04-29-release-notes-1.22/index.md
Labels: kind/bug, area/documentation, area/core-and-supporting, size/XS, lgtm

#879 Fix Algolia search and add .nvmrc file
  .nvmrc
  src/sitemetadata/extractor/docs.ts
Labels: area/core-and-supporting, size/XS, lgtm

#881 Fix broken links
  content/blog-posts/2022-03-25-release-notes-2.1/index.md
Labels: kind/bug, area/documentation, area/core-and-supporting, size/XS, lgtm

#882 Fix broken links
  content/blog-posts/2021-04-08-release-notes-1.21/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#884 observability blog post
  content/blog-posts/2022-09-21-observability-strategy/Indirect.png
  content/blog-posts/2022-09-21-observability-strategy/architecture.png
  content/blog-posts/2022-09-21-observability-strategy/custom.png
  content/blog-posts/2022-09-21-observability-strategy/direct.png
  content/blog-posts/2022-09-21-observability-strategy/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#878 Release Notes for 2.7
  content/blog-posts/2022-09-22-release-notes-2.7/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#885 Update CODEOWNERS
  CODEOWNERS
Labels: area/core-and-supporting, size/XS, lgtm

#886 Release notes for Kyma 2.6.3
  content/blog-posts/2022-09-22-release-notes-2.6.3/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#887 fix broken links in website repo
  content/blog-posts/2022-08-02-release-notes-2.5/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#891 Add missing quotation marks to recent blog posts' metadata and references to minors
  content/blog-posts/2022-08-25-release-notes-2.6/index.md
  content/blog-posts/2022-09-21-observability-strategy/index.md
  content/blog-posts/2022-09-22-release-notes-2.6.3/index.md
  content/blog-posts/2022-09-22-release-notes-2.7/index.md
  content/blog-posts/2022-09-26-release-notes-2.7.1/index.md
Labels: area/documentation, lgtm
