Repository kyma-project/website, pull requests merged in 2022-12, with the labels that each got.

#919 Fix link to Grafana derived fields
  content/blog-posts/2021-04-08-release-notes-1.21/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#923 Fix link to monitoring custom metrics example
  content/blog-posts/2019-09-09-release-notes-1.5/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#925 blog about monitoring deprecation
  content/blog-posts/2022-11-02-loki-deprecation/index.md
  content/blog-posts/2022-12-09-monitoring-deprecation/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#927 adapt robots.txt
  config.json
  plugins/kyma-project-robots-txt-plugin/gatsby-node.js
  src/views/docs/components/versionSwitcher/index.tsx
Labels: size/S, lgtm

#928 changing Algolia Index
  .devcontainer/devcontainer.json
  static/js/docsearch.min.js
Labels: area/core-and-supporting, size/S, lgtm

#931 Add nataliasitko to codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: area/core-and-supporting, size/XS, lgtm

#933 Adjust website content to sidecar injection annotation deprecation
  content/blog-posts/2019-07-08-extend-wordpress/wordpress-deployment.yaml
  content/blog-posts/2019-07-12-release-notes-1.3/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#934 Blog post on the deprecation of the Istio sidecar injection annotation
  content/blog-posts/2022-12-30-deprecation-of-istio-sidecar-injection-annotation/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm
