Repository kyma-project/website, pull requests merged in 2022-08, with the labels that each got.

#869 Add release notes for Kyma 2.5
  content/blog-posts/2022-08-02-release-notes-2.5/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#871 fix migration guide link
  content/blog-posts/2022-06-08-release-notes-2.3/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#873 Update CODEOWNERS
  CODEOWNERS
Labels: area/core-and-supporting, size/XS, lgtm

#872 Fix right-side navigation highlighting and navigating
  README.md
  src/components/generic-documentation/index.tsx
Labels: kind/bug, area/documentation, area/core-and-supporting, size/XS, lgtm

#874 release notes for 2.6
  content/blog-posts/2022-08-25-release-notes-2.6/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#876 fix link to api-gateway in RNs
  content/blog-posts/2019-09-09-release-notes-1.5/index.md
  content/blog-posts/2021-04-29-release-notes-1.22/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm
