Repository kyma-project/website, pull requests merged in 2022-10, with the labels that each got.

#888 blog post about kiali deprecation
  content/blog-posts/2022-10-10-Kiali-deprecation/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#895 Change the slack invite link
  config.json
Labels: area/core-and-supporting, size/XS, lgtm

#898 add release notes for 2.7.3
  content/blog-posts/2022-10-20-release-notes-2.7.3/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#899 Remove an outdated link
  content/blog-posts/2018-12-03-kyma-at-kubecon/index.md
Labels: area/community, area/documentation, size/XS, lgtm

#897 Release Notes for Kyma 2.8
  content/blog-posts/2022-10-21-release-notes-2.8/index.md
Labels: area/documentation, area/core-and-supporting, hacktoberfest-accepted, size/L, lgtm

#900 fix outdated links in RN 2.6
  content/blog-posts/2022-08-25-release-notes-2.6/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm
