Repository kyma-project/website, pull requests merged in 2022-03, with the labels that each got.

#833 Fix content fetcher bug
  README.md
  tools/content-loader/bin/main.ts
  tools/content-loader/src/prepare-docs/release-fetcher.ts
Labels: kind/bug, size/M, lgtm

#834 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/S, lgtm

#835 Remove version disclaimer
  content/i18n/en/landing-page.json
  src/views/landingPage/CheckItOut/index.tsx
  src/views/landingPage/CheckItOut/styled.ts
Labels: size/M, lgtm

#836 Get rid of CLI download instructions from homepage
  src/views/landingPage/CheckItOut/Termynal/Termynal.tsx
  src/views/landingPage/CheckItOut/Termynal/styled.tsx
  src/views/landingPage/CheckItOut/index.tsx
Labels: size/M, lgtm

#839 Create release notes for release 2.1
  content/blog-posts/2022-03-25-release-notes-2.1/index.md
Labels: area/documentation, area/core-and-supporting, size/L, lgtm

#842 Change the Website links to Kyma 2.0 docs to GitHub links
  content/blog-posts/2021-12-07-release-notes-2.0/index.md
Labels: kind/bug, area/documentation, area/core-and-supporting, size/S, lgtm

#843 Change numer of last releases
  config.json
Labels: area/core-and-supporting, do-not-merge/hold, size/XS, lgtm
