Repository kyma-project/website, pull requests merged in 2022-11, with the labels that each got.

#902 removed wrongly posted second blog post about loki deprecation
  content/blog-posts/2022-11-01-loki-deprecation/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#904 Update 2.8 release notes
  content/blog-posts/2022-10-21-release-notes-2.8/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#907 Remove instructions on how to contact or join Core SIG
  content/blog-posts/2019-02-20-core-sig/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#908 Release notes for Kyma 2.8.2
  content/blog-posts/2022-11-08-release-notes-2.8.2/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#911 Add the blog post on CNI plugin
  content/blog-posts/2022-11-15-breaking-change-CNI-plugin/index.md
Labels: area/documentation, area/service-mesh, area/core-and-supporting, size/S, lgtm

#912 RNs quick fix
  content/blog-posts/2022-11-08-release-notes-2.8.2/index.md
  content/blog-posts/2022-11-15-breaking-change-CNI-plugin/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#915 add release notes 2.9
  content/blog-posts/2022-11-22-release-notes-2.9/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#918 remove Maja from codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: area/core-and-supporting, size/S, lgtm
