Repository kyma-project/website, pull requests merged in 2022-02, with the labels that each got.

#819 add new code owners
  CODEOWNERS
Labels: size/XS, lgtm

#820 Fix broken links
  content/blog-posts/2018-09-24-start-with-person-service/index.md
  content/blog-posts/2019-07-31-kyma-collaboration-with-ory/index.md
Labels: bug, area/documentation, size/XS, lgtm

#825 fix broken link
  content/blog-posts/2019-10-18-release-notes-1.6/index.md
Labels: area/documentation, size/XS, lgtm

#829 Update stale.yml
  .github/stale.yml
Labels: size/XS

#831 Update codeowners
  CODEOWNERS
Labels: size/XS, lgtm
