Repository kyma-project/website, pull requests merged in 2023-03, with the labels that each got.

#959 remove link to telepresence
  content/blog-posts/2019-09-09-release-notes-1.5/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#962 remove Lyczeq
  CODEOWNERS
  OWNERS_ALIASES
Labels: area/core-and-supporting, size/XS, lgtm

#963 remove unnecessary link
  content/blog-posts/2021-04-08-release-notes-1.21/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#967 Add Release Notes 2.11.3
  content/blog-posts/2023-03-14-release-notes-2.11.3/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#968 remove security
  content/blog-posts/2023-03-14-release-notes-2.11.3/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#965 Release note Rel.2.12
  content/blog-posts/2023-03-15-release-notes-2.12/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#970 Fix broken links in RNs 2.10
  content/blog-posts/2023-01-17-release-notes-2.10/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#972 removed community pages
  Makefile
  src/layouts/default/components/Navigation.tsx
  static/_redirects
Labels: area/core-and-supporting, size/XS, lgtm

#971 Release notes for Kyma 2.12.1
  content/blog-posts/2023-03-30-release-notes-2.12.1/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm
