Repository kyma-project/website, pull requests merged in 2023-04, with the labels that each got.

#969 Adapt blogpost, kyma-cli argument change
  content/blog-posts/2023-01-11-istio-xff-support/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#974 Add release notes for Kyma 2.13
  content/blog-posts/2023-04-14-release-notes-2.13/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#975 Add a troubleshooting section to the RNs for Kyma 2.13
  content/blog-posts/2023-04-14-release-notes-2.13/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#976 Removed the blogposts and added redirects
  gatsby/node-api/pages/index.ts
  src/layouts/default/components/Navigation.tsx
  static/_redirects
Labels: area/core-and-supporting, size/M, lgtm

#977 Update redirects
  static/_redirects
Labels: area/core-and-supporting, size/S, lgtm

#978 Add Gosia to CODEOWNERS
  CODEOWNERS
  OWNERS_ALIASES
Labels: area/core-and-supporting, size/XS, lgtm
