Repository kyma-project/website, pull requests merged in 2023-02, with the labels that each got.

#946 Remove Key Features section from landing page
  src/views/landingPage/index.tsx
Labels: area/core-and-supporting, size/XS, lgtm

#950 blog post about the API Gateway architecture change
  content/blog-posts/2023-02-09-change-of-api-gateway-architecture/api-gateway-deps.png
  content/blog-posts/2023-02-09-change-of-api-gateway-architecture/api-gateway-future-deps.png
  content/blog-posts/2023-02-09-change-of-api-gateway-architecture/index.md
  content/blog-posts/2023-02-09-change-of-api-gateway-architecture/jwt-flow.png
  content/blog-posts/2023-02-09-change-of-api-gateway-architecture/jwt-future.png
  content/blog-posts/2023-02-09-change-of-api-gateway-architecture/oauth2-flow.png
  content/blog-posts/2023-02-09-change-of-api-gateway-architecture/oauth2-future.png
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#948 2.11 release notes
  content/blog-posts/2023-02-13-release-notes-2.11/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#952 Fix release tag
  content/blog-posts/2023-01-17-release-notes-2.10/index.md
  content/blog-posts/2023-02-13-release-notes-2.11/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#953 Fix tag
  content/blog-posts/2023-02-13-release-notes-2.11/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#955 Fix the title
  content/blog-posts/2023-02-13-release-notes-2.11/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#956 fix a link
  content/blog-posts/2023-01-11-istio-xff-support/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#957 Update adopters.yaml
  content/adopters/adopters.yaml
Labels: area/core-and-supporting, size/XS, lgtm
