Repository kyma-project/website, pull requests merged in 2023-01, with the labels that each got.

#935 remove Daria and Piotr as CODEOWNERS :sadcat:
  CODEOWNERS
Labels: area/core-and-supporting, size/XS, lgtm

#917 Blog post for Istio XFF support
  content/blog-posts/2022-11-18-istio-xff-support/index.md
Labels: area/documentation, area/core-and-supporting, size/L, lgtm

#938 change the date
  content/blog-posts/2023-01-11-istio-xff-support/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm

#939 Release Notes for Kyma 2.10
  content/blog-posts/2023-01-17-release-notes-2.10/index.md
Labels: area/documentation, area/core-and-supporting, size/M, lgtm

#941 blog post deprecating jaeger component - tracing module
  content/blog-posts/2023-01-16-jaeger-deprecation/index.md
Labels: area/documentation, area/core-and-supporting, size/S, lgtm

#944 fix broken links in 2.8 RNs
  content/blog-posts/2022-10-21-release-notes-2.8/index.md
Labels: area/documentation, area/core-and-supporting, size/XS, lgtm
